


from PyQt5 import QtCore, QtGui, QtWidgets


class DonateWindow(QtWidgets.QWidget):
    def __init__(self):
        self.setObjectName("Form")
        self.resize(556, 234)
        self.groupBox = QtWidgets.QGroupBox(self)
        self.groupBox.setGeometry(QtCore.QRect(5, 5, 541, 216))
        self.groupBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(5, 30, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(5, 60, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(5, 90, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(5, 120, 67, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(105, 60, 420, 17))
        self.label_5.setAutoFillBackground(True)
        self.label_5.setText("")
        self.label_5.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(105, 120, 420, 17))
        self.label_6.setAutoFillBackground(True)
        self.label_6.setText("")
        self.label_6.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(105, 30, 420, 17))
        self.label_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.label_7.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.label_7.setAutoFillBackground(True)
        self.label_7.setText("")
        self.label_7.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_7.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(105, 90, 420, 17))
        self.label_8.setAutoFillBackground(True)
        self.label_8.setText("")
        self.label_8.setScaledContents(True)
        self.label_8.setWordWrap(True)
        self.label_8.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(5, 155, 521, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(5, 185, 521, 17))
        self.label_10.setObjectName("label_10")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "ADDRESSES: "))
        self.label.setText(_translate("Form", "BTC:"))
        self.label_2.setText(_translate("Form", "ETH:"))
        self.label_3.setText(_translate("Form", "ADA:"))
        self.label_4.setText(_translate("Form", "DOT:"))
        self.label_9.setText(_translate("Form", "If you like Datazaur, feel free to donate to support open data initiative."))
        self.label_10.setText(_translate("Form", "Datazaur is, and always will be, free of charge and open-source."))

