
from PyQt5 import QtCore, QtGui, QtWidgets
from ui.widgets.markets.markets_widget import MarketsWidget
from ui.widgets.trade.trade_widget import TradeWidget
from ui.widgets.algorithm_wizard import AlgorithmWizard
from ui.widgets.charts_widget import ChartsWidget
from ui.widgets.database_widget import DatabaseWidget
from ui.widgets.donate_window import DonateWindow
from ui.widgets.news_widget import NewsWidget
from ui.widgets.scripts_widget import ScriptsWidget
from ui.widgets.watchlist_widget import WatchlistWidget
import datetime
import pandas as pd


class FrontZaur(QtWidgets.QMainWindow):
    def __init__(self, datazaur):
        super().__init__()

        self.datazaur = datazaur
        self.apps = {
            'markets': MarketsWidget(),
            'trade': TradeWidget(),
            'charts': ChartsWidget(),
            'watchlist': WatchlistWidget(),
            'wizard': AlgorithmWizard(),
            'news': NewsWidget(),
            'scripts': ScriptsWidget()
        }


        self.setObjectName("self")
        self.resize(1225, 767)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1211, 721))
        self.widget.setObjectName("widget")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(5, 0, 1206, 721))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget1)
        self.groupBox.setMinimumSize(QtCore.QSize(220, 700))
        self.groupBox.setMaximumSize(QtCore.QSize(250, 800))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(8, 27, 131, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(148, 27, 66, 25))
        self.pushButton.setObjectName("pushButton")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setGeometry(QtCore.QRect(5, 60, 211, 131))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 209, 129))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(5, 5, 196, 116))
        self.listWidget.setObjectName("listWidget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 380, 216, 136))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(5, 30, 71, 23))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(5, 65, 66, 23))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(5, 100, 71, 23))
        self.radioButton_3.setObjectName("radioButton_3")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(90, 30, 121, 23))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_2)
        self.dateTimeEdit.setGeometry(QtCore.QRect(90, 65, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.groupBox_2)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(90, 100, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateTimeEdit_2.setFont(font)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 200, 211, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 30, 89, 26))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setGeometry(QtCore.QRect(115, 30, 89, 26))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(115, 65, 89, 26))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 135, 194, 26))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 65, 89, 26))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setGeometry(QtCore.QRect(115, 100, 89, 26))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 100, 89, 26))
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout.addWidget(self.groupBox)
        self.tabWidget = QtWidgets.QTabWidget(self.widget1)
        self.tabWidget.setMinimumSize(QtCore.QSize(700, 600))
        self.tabWidget.setMaximumSize(QtCore.QSize(978, 719))
        self.tabWidget.setObjectName("tabWidget")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1225, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAnalysis = QtWidgets.QMenu(self.menubar)
        self.menuAnalysis.setObjectName("menuAnalysis")
        self.menuStationarity = QtWidgets.QMenu(self.menuAnalysis)
        self.menuStationarity.setObjectName("menuStationarity")
        self.menuCointegration = QtWidgets.QMenu(self.menuAnalysis)
        self.menuCointegration.setObjectName("menuCointegration")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuThemes = QtWidgets.QMenu(self.menuSettings)
        self.menuThemes.setObjectName("menuThemes")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionMarkets = QtWidgets.QAction(self)
        self.actionMarkets.setCheckable(True)
        self.actionMarkets.setChecked(True)
        self.actionMarkets.setObjectName("actionMarkets")
        self.actionTrade = QtWidgets.QAction(self)
        self.actionTrade.setCheckable(True)
        self.actionTrade.setChecked(True)
        self.actionTrade.setObjectName("actionTrade")
        self.actionCharts = QtWidgets.QAction(self)
        self.actionCharts.setCheckable(True)
        self.actionCharts.setChecked(True)
        self.actionCharts.setObjectName("actionCharts")
        self.actionWatchlist = QtWidgets.QAction(self)
        self.actionWatchlist.setCheckable(True)
        self.actionWatchlist.setChecked(True)
        self.actionWatchlist.setObjectName("actionWatchlist")
        self.actionAlgorithm_Wizard = QtWidgets.QAction(self)
        self.actionAlgorithm_Wizard.setCheckable(True)
        self.actionAlgorithm_Wizard.setChecked(True)
        self.actionAlgorithm_Wizard.setObjectName("actionAlgorithm_Wizard")
        self.actionPortfolio = QtWidgets.QAction(self)
        self.actionPortfolio.setObjectName("actionPortfolio")
        self.actionScript_Editor = QtWidgets.QAction(self)
        self.actionScript_Editor.setCheckable(True)
        self.actionScript_Editor.setChecked(True)
        self.actionScript_Editor.setObjectName("actionScript_Editor")
        self.actionDatabase = QtWidgets.QAction(self)
        self.actionDatabase.setObjectName("actionDatabase")
        self.actionNews_Feed = QtWidgets.QAction(self)
        self.actionNews_Feed.setCheckable(True)
        self.actionNews_Feed.setChecked(True)
        self.actionNews_Feed.setObjectName("actionNews_Feed")
        self.actionSettings = QtWidgets.QAction(self)
        self.actionSettings.setObjectName("actionSettings")
        self.actionNavy = QtWidgets.QAction(self)
        self.actionNavy.setObjectName("actionNavy")
        self.actionMatrix = QtWidgets.QAction(self)
        self.actionMatrix.setObjectName("actionMatrix")
        self.actionAbout = QtWidgets.QAction(self)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDonate = QtWidgets.QAction(self)
        self.actionDonate.setObjectName("actionDonate")
        self.actionContribute = QtWidgets.QAction(self)
        self.actionContribute.setObjectName("actionContribute")
        self.actionHelp = QtWidgets.QAction(self)
        self.actionHelp.setObjectName("actionHelp")
        self.actionADF = QtWidgets.QAction(self)
        self.actionADF.setObjectName("actionADF")
        self.actionKPSS_test = QtWidgets.QAction(self)
        self.actionKPSS_test.setObjectName("actionKPSS_test")
        self.actionEngle_Granger_test = QtWidgets.QAction(self)
        self.actionEngle_Granger_test.setObjectName("actionEngle_Granger_test")
        self.actionJohansen = QtWidgets.QAction(self)
        self.actionJohansen.setObjectName("actionJohansen")
        self.actionBacktest = QtWidgets.QAction(self)
        self.actionBacktest.setObjectName("actionBacktest")
        self.actionCustom = QtWidgets.QAction(self)
        self.actionCustom.setObjectName("actionCustom")
        self.actionFX_Rates = QtWidgets.QAction(self)
        self.actionFX_Rates.setObjectName("actionFX_Rates")
        self.menuStationarity.addAction(self.actionADF)
        self.menuStationarity.addAction(self.actionKPSS_test)
        self.menuCointegration.addAction(self.actionEngle_Granger_test)
        self.menuCointegration.addAction(self.actionJohansen)
        self.menuAnalysis.addAction(self.menuStationarity.menuAction())
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.menuCointegration.menuAction())
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.actionBacktest)
        self.menuView.addAction(self.actionMarkets)
        self.menuView.addAction(self.actionTrade)
        self.menuView.addAction(self.actionCharts)
        self.menuView.addAction(self.actionWatchlist)
        self.menuView.addAction(self.actionAlgorithm_Wizard)
        self.menuView.addAction(self.actionNews_Feed)
        self.menuView.addAction(self.actionScript_Editor)
        self.menuView.addAction(self.actionFX_Rates)
        self.menuView.addAction(self.actionPortfolio)
        self.menuView.addAction(self.actionDatabase)
        self.menuView.addSeparator()
        self.menuThemes.addAction(self.actionNavy)
        self.menuThemes.addAction(self.actionMatrix)
        self.menuThemes.addSeparator()
        self.menuThemes.addAction(self.actionCustom)
        self.menuSettings.addAction(self.actionSettings)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.menuThemes.menuAction())
        self.menuSettings.addSeparator()
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionContribute)
        self.menuHelp.addAction(self.actionDonate)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "Datazaur"))
        self.groupBox.setTitle(_translate("self", "  DATAZAUR"))
        self.pushButton.setText(_translate("self", "SEARCH"))
        self.groupBox_2.setTitle(_translate("self", "  TIMEFRAME "))
        self.radioButton.setToolTip(_translate("self", "<html><head/><body><p>If \'LAST\' is selected, only timeframe must be specified and end date is set as now.</p></body></html>"))
        self.radioButton.setText(_translate("self", "LAST"))
        self.radioButton_2.setToolTip(_translate("self", "<html><head/><body><p>If \'SINCE\' is selected, only start date must be specified and end date is set as now.</p></body></html>"))
        self.radioButton_2.setText(_translate("self", "SINCE"))
        self.radioButton_3.setToolTip(_translate("self", "<html><head/><body><p>If \'RANGE\' is selected, both start and end dates must be specified. </p><p>This option allows examination of any chosen timeframe.</p><p>Start date is in top dateedit and end date is in bottom one.</p></body></html>"))
        self.radioButton_3.setText(_translate("self", "RANGE"))
        self.comboBox.setItemText(0, _translate("self", "12h"))
        self.comboBox.setItemText(1, _translate("self", "1d"))
        self.comboBox.setItemText(2, _translate("self", "2d"))
        self.comboBox.setItemText(3, _translate("self", "3d"))
        self.comboBox.setItemText(4, _translate("self", "1w"))
        self.comboBox.setItemText(5, _translate("self", "2w"))
        self.comboBox.setItemText(6, _translate("self", "1M"))
        self.comboBox.setItemText(7, _translate("self", "2M"))
        self.comboBox.setItemText(8, _translate("self", "3M"))
        self.comboBox.setItemText(9, _translate("self", "6M"))
        self.comboBox.setItemText(10, _translate("self", "9M"))
        self.comboBox.setItemText(11, _translate("self", "1Y"))
        self.comboBox.setItemText(12, _translate("self", "2Y"))
        self.comboBox.setItemText(13, _translate("self", "3Y"))
        self.comboBox.setItemText(14, _translate("self", "5Y"))
        self.comboBox.setItemText(15, _translate("self", "8Y"))
        self.comboBox.setItemText(16, _translate("self", "10Y"))
        self.comboBox.setItemText(17, _translate("self", "ALL DATA"))
        self.groupBox_3.setTitle(_translate("self", "  ACTIONS "))
        self.pushButton_2.setText(_translate("self", "WATCH"))
        self.pushButton_3.setText(_translate("self", "CHART"))
        self.pushButton_4.setText(_translate("self", "TRADE"))
        self.pushButton_5.setText(_translate("self", "CALCULATE RETURN"))
        self.pushButton_6.setText(_translate("self", "QUOTE"))
        self.pushButton_7.setText(_translate("self", "VARIABLES"))
        self.pushButton_8.setText(_translate("self", "ALERT"))
        self.menuFile.setTitle(_translate("self", "File"))
        self.menuAnalysis.setTitle(_translate("self", "Analysis"))
        self.menuStationarity.setTitle(_translate("self", "Stationarity"))
        self.menuCointegration.setTitle(_translate("self", "Cointegration"))
        self.menuView.setTitle(_translate("self", "View"))
        self.menuSettings.setTitle(_translate("self", "Settings"))
        self.menuThemes.setTitle(_translate("self", "Themes"))
        self.menuHelp.setTitle(_translate("self", "Help"))
        self.actionMarkets.setText(_translate("self", "Markets"))
        self.actionTrade.setText(_translate("self", "Trade"))
        self.actionCharts.setText(_translate("self", "Charts"))
        self.actionWatchlist.setText(_translate("self", "Watchlist"))
        self.actionAlgorithm_Wizard.setText(_translate("self", "Algorithm Wizard"))
        self.actionPortfolio.setText(_translate("self", "Portfolio Manager"))
        self.actionScript_Editor.setText(_translate("self", "Script Editor"))
        self.actionDatabase.setText(_translate("self", "Database"))
        self.actionNews_Feed.setText(_translate("self", "News Feed"))
        self.actionSettings.setText(_translate("self", "Settings"))
        self.actionNavy.setText(_translate("self", "Navy"))
        self.actionMatrix.setText(_translate("self", "Matrix"))
        self.actionAbout.setText(_translate("self", "About"))
        self.actionDonate.setText(_translate("self", "Donate"))
        self.actionContribute.setText(_translate("self", "Contribute"))
        self.actionHelp.setText(_translate("self", "Help"))
        self.actionADF.setText(_translate("self", "ADF test"))
        self.actionKPSS_test.setText(_translate("self", "KPSS test"))
        self.actionEngle_Granger_test.setText(_translate("self", "Engle-Granger"))
        self.actionJohansen.setText(_translate("self", "Johansen"))
        self.actionBacktest.setText(_translate("self", "Backtest"))
        self.actionCustom.setText(_translate("self", "Custom"))
        self.actionFX_Rates.setText(_translate("self", "FX Rates"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = FrontZaur(app)
    ui.show()
    sys.exit(app.exec_())
