from PyQt5 import QtCore, QtGui, QtWidgets
from ui.widgets.markets.markets_widget import MarketsWidget
from ui.widgets.trade.trade_widget import TradeWidget
from ui.widgets.algorithm_wizard import AlgorithmWizard
from ui.widgets.charts_widget import ChartsWidget
from ui.widgets.database_widget import DatabaseWidget
from ui.widgets.date_selector import DateSelector
from ui.widgets.donate_window import DonateWindow
from ui.widgets.news_widget import NewsWidget
from ui.widgets.scripts_widget import ScriptsWidget
from ui.widgets.watchlist_widget import WatchlistWidget
import datetime
import pandas as pd


class FrontZaur(QtWidgets.QMainWindow):
    def __init__(self, datazaur):
        super().__init__()
        self.datazaur = datazaur

        self.apps = {
            'markets': MarketsWidget(),
            'trade': TradeWidget(),
            'charts': ChartsWidget(),
            'watchlist': WatchlistWidget(),
            'wizard': AlgorithmWizard(),
            'news': NewsWidget(),
            'scripts': ScriptsWidget()
        }


        self.setObjectName("self")
        self.resize(1220, 765)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 23, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 16, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 13, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 7, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 35, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 11, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 3, 28))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 9, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 23, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 16, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 13, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 5, 19))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 7, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 35, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 11, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 3, 28))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 9, 59))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 23, 39))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(18, 16, 56))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 13, 46))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(6, 5, 19))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(8, 7, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 239, 239))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(9, 35, 54))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 11, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 145, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 11, 37))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.setFont(font)
        self.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setMinimumSize(QtCore.QSize(715, 404))
        self.centralwidget.setMaximumSize(QtCore.QSize(1429, 808))
        palette = QtGui.QPalette()
        self.centralwidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1216, 711))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.horizontalLayoutWidget.setFont(font)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(1, 3, 1, 3)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(100, 400))
        self.groupBox_2.setMaximumSize(QtCore.QSize(220, 700))
        self.groupBox_2.setSizeIncrement(QtCore.QSize(4, 4))
        self.groupBox_2.setBaseSize(QtCore.QSize(240, 700))
        palette = QtGui.QPalette()
        self.groupBox_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setMouseTracking(False)
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_29 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_29.setGeometry(QtCore.QRect(5, 545, 211, 151))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox_29.setFont(font)
        self.groupBox_29.setStyleSheet("")
        self.groupBox_29.setCheckable(False)
        self.groupBox_29.setChecked(False)
        self.groupBox_29.setObjectName("groupBox_29")
        self.dateTimeEdit_3 = QtWidgets.QDateTimeEdit(self.groupBox_29)
        self.dateTimeEdit_3.setEnabled(True)
        self.dateTimeEdit_3.setGeometry(QtCore.QRect(70, 90, 136, 23))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.dateTimeEdit_3.setFont(font)
        self.dateTimeEdit_3.setStyleSheet("")
        self.dateTimeEdit_3.setObjectName("dateTimeEdit_3")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_29)
        self.radioButton.setGeometry(QtCore.QRect(15, 30, 56, 23))
        self.radioButton.setStyleSheet("")
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_29)
        self.radioButton_2.setGeometry(QtCore.QRect(15, 60, 61, 23))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("")
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.comboBox_37 = QtWidgets.QComboBox(self.groupBox_29)
        self.comboBox_37.setEnabled(False)
        self.comboBox_37.setGeometry(QtCore.QRect(110, 30, 76, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.comboBox_37.setFont(font)
        self.comboBox_37.setStyleSheet("")
        self.comboBox_37.setObjectName("comboBox_37")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.comboBox_37.addItem("")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_29)
        self.radioButton_3.setGeometry(QtCore.QRect(110, 60, 76, 23))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("")
        self.radioButton_3.setChecked(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.dateTimeEdit_4 = QtWidgets.QDateTimeEdit(self.groupBox_29)
        self.dateTimeEdit_4.setEnabled(False)
        self.dateTimeEdit_4.setGeometry(QtCore.QRect(70, 120, 136, 23))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.dateTimeEdit_4.setFont(font)
        self.dateTimeEdit_4.setStyleSheet("")
        self.dateTimeEdit_4.setObjectName("dateTimeEdit_4")
        self.label = QtWidgets.QLabel(self.groupBox_29)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(20, 120, 41, 23))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_29)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 41, 23))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.groupBox_24 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_24.setGeometry(QtCore.QRect(0, 110, 216, 196))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox_24.setFont(font)
        self.groupBox_24.setStyleSheet("")
        self.groupBox_24.setObjectName("groupBox_24")
        self.listWidget_17 = QtWidgets.QListWidget(self.groupBox_24)
        self.listWidget_17.setGeometry(QtCore.QRect(5, 25, 206, 166))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.listWidget_17.setFont(font)
        self.listWidget_17.setStyleSheet("")
        self.listWidget_17.setObjectName("listWidget_17")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_8.setGeometry(QtCore.QRect(5, 310, 211, 226))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_6.setGeometry(QtCore.QRect(115, 65, 86, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_48 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_48.setGeometry(QtCore.QRect(10, 65, 86, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_48.setFont(font)
        self.pushButton_48.setStyleSheet("")
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_49 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_49.setGeometry(QtCore.QRect(115, 105, 86, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_49.setFont(font)
        self.pushButton_49.setObjectName("pushButton_49")
        self.pushButton_50 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_50.setGeometry(QtCore.QRect(115, 145, 86, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_50.setFont(font)
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_53 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_53.setGeometry(QtCore.QRect(10, 105, 86, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_53.setFont(font)
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_80 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_80.setGeometry(QtCore.QRect(10, 145, 86, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_80.setFont(font)
        self.pushButton_80.setObjectName("pushButton_80")
        self.label_16 = QtWidgets.QLabel(self.groupBox_8)
        self.label_16.setGeometry(QtCore.QRect(15, 30, 81, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        self.pushButton_82 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_82.setGeometry(QtCore.QRect(10, 185, 191, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_82.setFont(font)
        self.pushButton_82.setObjectName("pushButton_82")
        self.pushButton_81 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_81.setGeometry(QtCore.QRect(150, 50, 66, 24))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_81.setFont(font)
        self.pushButton_81.setStyleSheet("")
        self.pushButton_81.setObjectName("pushButton_81")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_4.setGeometry(QtCore.QRect(5, 80, 71, 23))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setStyleSheet("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.comboBox_36 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_36.setEnabled(False)
        self.comboBox_36.setGeometry(QtCore.QRect(110, 80, 106, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.comboBox_36.setFont(font)
        self.comboBox_36.setStyleSheet("")
        self.comboBox_36.setObjectName("comboBox_36")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.comboBox_36.addItem("")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(5, 50, 136, 24))
        self.lineEdit_7.setMinimumSize(QtCore.QSize(91, 24))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setAcceptDrops(True)
        self.lineEdit_7.setAutoFillBackground(False)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(600, 400))
        self.groupBox_3.setMaximumSize(QtCore.QSize(970, 700))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_3)
        self.tabWidget.setGeometry(QtCore.QRect(5, 5, 956, 691))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1225, 20))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.menuFile.setFont(font)
        self.menuFile.setAcceptDrops(False)
        self.menuFile.setAutoFillBackground(False)
        self.menuFile.setTearOffEnabled(False)
        self.menuFile.setSeparatorsCollapsible(False)
        self.menuFile.setObjectName("menuFile")
        self.menuSave = QtWidgets.QMenu(self.menuFile)
        self.menuSave.setObjectName("menuSave")
        self.menuAlgorithm = QtWidgets.QMenu(self.menuSave)
        self.menuAlgorithm.setObjectName("menuAlgorithm")
        self.menuExchange = QtWidgets.QMenu(self.menuSave)
        self.menuExchange.setObjectName("menuExchange")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.menuSettings.setFont(font)
        self.menuSettings.setAcceptDrops(False)
        self.menuSettings.setAutoFillBackground(False)
        self.menuSettings.setTearOffEnabled(False)
        self.menuSettings.setSeparatorsCollapsible(False)
        self.menuSettings.setObjectName("menuSettings")
        self.menuTheme = QtWidgets.QMenu(self.menuSettings)
        self.menuTheme.setObjectName("menuTheme")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.menuHelp.setFont(font)
        self.menuHelp.setAcceptDrops(False)
        self.menuHelp.setAutoFillBackground(False)
        self.menuHelp.setTearOffEnabled(False)
        self.menuHelp.setSeparatorsCollapsible(False)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAnalysis = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.menuAnalysis.setFont(font)
        self.menuAnalysis.setAcceptDrops(False)
        self.menuAnalysis.setAutoFillBackground(False)
        self.menuAnalysis.setTearOffEnabled(False)
        self.menuAnalysis.setSeparatorsCollapsible(False)
        self.menuAnalysis.setObjectName("menuAnalysis")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionSave_all = QtWidgets.QAction(self)
        self.actionSave_all.setObjectName("actionSave_all")
        self.actionAll_exchanges = QtWidgets.QAction(self)
        self.actionAll_exchanges.setObjectName("actionAll_exchanges")
        self.actionSave_all_2 = QtWidgets.QAction(self)
        self.actionSave_all_2.setObjectName("actionSave_all_2")
        self.actionAccount = QtWidgets.QAction(self)
        self.actionAccount.setObjectName("actionAccount")
        self.actionLog_out = QtWidgets.QAction(self)
        self.actionLog_out.setObjectName("actionLog_out")
        self.actionExit = QtWidgets.QAction(self)
        self.actionExit.setObjectName("actionExit")
        self.actionOpen = QtWidgets.QAction(self)
        self.actionOpen.setObjectName("actionOpen")
        self.actionCrypto = QtWidgets.QAction(self)
        self.actionCrypto.setObjectName("actionCrypto")
        self.actionEquities = QtWidgets.QAction(self)
        self.actionEquities.setObjectName("actionEquities")
        self.actionIndexes = QtWidgets.QAction(self)
        self.actionIndexes.setObjectName("actionIndexes")
        self.actionFX = QtWidgets.QAction(self)
        self.actionFX.setObjectName("actionFX")
        self.actionMacro = QtWidgets.QAction(self)
        self.actionMacro.setObjectName("actionMacro")
        self.actionFundamentals = QtWidgets.QAction(self)
        self.actionFundamentals.setObjectName("actionFundamentals")
        self.actionFixed_Income = QtWidgets.QAction(self)
        self.actionFixed_Income.setObjectName("actionFixed_Income")
        self.actionCharts = QtWidgets.QAction(self)
        self.actionCharts.setCheckable(True)
        self.actionCharts.setChecked(True)
        self.actionCharts.setObjectName("actionCharts")
        self.actionAlgorithm_Wizard = QtWidgets.QAction(self)
        self.actionAlgorithm_Wizard.setCheckable(True)
        self.actionAlgorithm_Wizard.setChecked(True)
        self.actionAlgorithm_Wizard.setObjectName("actionAlgorithm_Wizard")
        self.actionPortfolio_Manager = QtWidgets.QAction(self)
        self.actionPortfolio_Manager.setCheckable(True)
        self.actionPortfolio_Manager.setObjectName("actionPortfolio_Manager")
        self.actionWatchlist = QtWidgets.QAction(self)
        self.actionWatchlist.setCheckable(True)
        self.actionWatchlist.setChecked(True)
        self.actionWatchlist.setObjectName("actionWatchlist")
        self.actionMarket_Alerts = QtWidgets.QAction(self)
        self.actionMarket_Alerts.setCheckable(True)
        self.actionMarket_Alerts.setChecked(True)
        self.actionMarket_Alerts.setObjectName("actionMarket_Alerts")
        self.actionTwitter_Monitor = QtWidgets.QAction(self)
        self.actionTwitter_Monitor.setCheckable(True)
        self.actionTwitter_Monitor.setObjectName("actionTwitter_Monitor")
        self.actionCurrency_Converter = QtWidgets.QAction(self)
        self.actionCurrency_Converter.setCheckable(True)
        self.actionCurrency_Converter.setObjectName("actionCurrency_Converter")
        self.actionBacktest_Simulator = QtWidgets.QAction(self)
        self.actionBacktest_Simulator.setObjectName("actionBacktest_Simulator")
        self.actionConfig = QtWidgets.QAction(self)
        self.actionConfig.setObjectName("actionConfig")
        self.actionPreferences = QtWidgets.QAction(self)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionDatabase = QtWidgets.QAction(self)
        self.actionDatabase.setObjectName("actionDatabase")
        self.actionDatazaur_Help = QtWidgets.QAction(self)
        self.actionDatazaur_Help.setObjectName("actionDatazaur_Help")
        self.actionContribute = QtWidgets.QAction(self)
        self.actionContribute.setObjectName("actionContribute")
        self.actionDonate = QtWidgets.QAction(self)
        self.actionDonate.setObjectName("actionDonate")
        self.actionAbout_Datazaur = QtWidgets.QAction(self)
        self.actionAbout_Datazaur.setObjectName("actionAbout_Datazaur")
        self.actionDark_navy = QtWidgets.QAction(self)
        self.actionDark_navy.setObjectName("actionDark_navy")
        self.actionLight = QtWidgets.QAction(self)
        self.actionLight.setObjectName("actionLight")
        self.actionCustom = QtWidgets.QAction(self)
        self.actionCustom.setObjectName("actionCustom")
        self.actionDatabase_2 = QtWidgets.QAction(self)
        self.actionDatabase_2.setCheckable(True)
        self.actionDatabase_2.setObjectName("actionDatabase_2")
        self.actionEXPLORER = QtWidgets.QAction(self)
        self.actionEXPLORER.setCheckable(True)
        self.actionEXPLORER.setChecked(True)
        self.actionEXPLORER.setObjectName("actionEXPLORER")
        self.actionCrypto_Overview = QtWidgets.QAction(self)
        self.actionCrypto_Overview.setCheckable(True)
        self.actionCrypto_Overview.setObjectName("actionCrypto_Overview")
        self.actionADF_Test = QtWidgets.QAction(self)
        self.actionADF_Test.setObjectName("actionADF_Test")
        self.actionKPSS_Test = QtWidgets.QAction(self)
        self.actionKPSS_Test.setObjectName("actionKPSS_Test")
        self.actionEngle_Granger_Test = QtWidgets.QAction(self)
        self.actionEngle_Granger_Test.setObjectName("actionEngle_Granger_Test")
        self.actionBacktest = QtWidgets.QAction(self)
        self.actionBacktest.setObjectName("actionBacktest")
        self.actionCrypto_Wallet = QtWidgets.QAction(self)
        self.actionCrypto_Wallet.setCheckable(True)
        self.actionCrypto_Wallet.setObjectName("actionCrypto_Wallet")
        self.actionNews_Feed = QtWidgets.QAction(self)
        self.actionNews_Feed.setCheckable(True)
        self.actionNews_Feed.setChecked(True)
        self.actionNews_Feed.setObjectName("actionNews_Feed")
        self.actionCustom_Scripts = QtWidgets.QAction(self)
        self.actionCustom_Scripts.setCheckable(True)
        self.actionCustom_Scripts.setChecked(True)
        self.actionCustom_Scripts.setObjectName("actionCustom_Scripts")
        self.actionMarkets = QtWidgets.QAction(self)
        self.actionMarkets.setCheckable(True)
        self.actionMarkets.setChecked(True)
        self.actionMarkets.setObjectName("actionMarkets")
        self.actionTrading = QtWidgets.QAction(self)
        self.actionTrading.setCheckable(True)
        self.actionTrading.setChecked(True)
        self.actionTrading.setObjectName("actionTrading")
        self.actionMatrix = QtWidgets.QAction(self)
        self.actionMatrix.setObjectName("actionMatrix")
        self.actionMarkets_2 = QtWidgets.QAction(self)
        self.actionMarkets_2.setCheckable(True)
        self.actionMarkets_2.setChecked(True)
        self.actionMarkets_2.setObjectName("actionMarkets_2")
        self.actionTrading_2 = QtWidgets.QAction(self)
        self.actionTrading_2.setCheckable(True)
        self.actionTrading_2.setChecked(True)
        self.actionTrading_2.setObjectName("actionTrading_2")
        self.actionCharts_2 = QtWidgets.QAction(self)
        self.actionCharts_2.setCheckable(True)
        self.actionCharts_2.setChecked(True)
        self.actionCharts_2.setObjectName("actionCharts_2")
        self.actionWatchlist_2 = QtWidgets.QAction(self)
        self.actionWatchlist_2.setCheckable(True)
        self.actionWatchlist_2.setChecked(True)
        self.actionWatchlist_2.setObjectName("actionWatchlist_2")
        self.actionAlgorithm_Wizard_2 = QtWidgets.QAction(self)
        self.actionAlgorithm_Wizard_2.setCheckable(True)
        self.actionAlgorithm_Wizard_2.setChecked(True)
        self.actionAlgorithm_Wizard_2.setObjectName("actionAlgorithm_Wizard_2")
        self.actionNews_Feed_2 = QtWidgets.QAction(self)
        self.actionNews_Feed_2.setCheckable(True)
        self.actionNews_Feed_2.setChecked(True)
        self.actionNews_Feed_2.setObjectName("actionNews_Feed_2")
        self.actionScript_Editor = QtWidgets.QAction(self)
        self.actionScript_Editor.setCheckable(True)
        self.actionScript_Editor.setChecked(True)
        self.actionScript_Editor.setObjectName("actionScript_Editor")
        self.actionPortfolio_Manager_2 = QtWidgets.QAction(self)
        self.actionPortfolio_Manager_2.setObjectName("actionPortfolio_Manager_2")
        self.actionDatabase_3 = QtWidgets.QAction(self)
        self.actionDatabase_3.setObjectName("actionDatabase_3")
        self.actionDocs = QtWidgets.QAction(self)
        self.actionDocs.setObjectName("actionDocs")
        self.menuAlgorithm.addAction(self.actionSave_all)
        self.menuAlgorithm.addSeparator()
        self.menuExchange.addAction(self.actionAll_exchanges)
        self.menuSave.addAction(self.menuAlgorithm.menuAction())
        self.menuSave.addAction(self.menuExchange.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addAction(self.actionSave_all_2)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionAccount)
        self.menuFile.addAction(self.actionLog_out)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuTheme.addAction(self.actionDark_navy)
        self.menuTheme.addAction(self.actionMatrix)
        self.menuTheme.addAction(self.actionLight)
        self.menuTheme.addSeparator()
        self.menuTheme.addAction(self.actionCustom)
        self.menuSettings.addAction(self.actionConfig)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.menuTheme.menuAction())
        self.menuHelp.addAction(self.actionDatazaur_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionContribute)
        self.menuHelp.addAction(self.actionDonate)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionDocs)
        self.menuHelp.addAction(self.actionAbout_Datazaur)
        self.menuAnalysis.addAction(self.actionADF_Test)
        self.menuAnalysis.addAction(self.actionKPSS_Test)
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.actionEngle_Granger_Test)
        self.menuAnalysis.addSeparator()
        self.menuAnalysis.addAction(self.actionBacktest)
        self.menuView.addAction(self.actionMarkets_2)
        self.menuView.addAction(self.actionTrading_2)
        self.menuView.addAction(self.actionCharts_2)
        self.menuView.addAction(self.actionWatchlist_2)
        self.menuView.addAction(self.actionAlgorithm_Wizard_2)
        self.menuView.addAction(self.actionNews_Feed_2)
        self.menuView.addAction(self.actionScript_Editor)
        self.menuView.addAction(self.actionPortfolio_Manager_2)
        self.menuView.addAction(self.actionDatabase_3)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.disable_inactive_widgets()
        self.retranslateUi()
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(self)

        self.radioButton.clicked.connect(self.select_timeframe)
        self.radioButton_2.clicked.connect(self.select_timeframe)
        self.radioButton_3.clicked.connect(self.select_timeframe)

    def disable_inactive_widgets(self):
        self.comboBox_37.setDisabled(True)
        self.dateTimeEdit_3.setEnabled(True)
        self.dateTimeEdit_4.setDisabled(True)
        self.dateTimeEdit_4.setDate(datetime.date.today())

    def open_app(self, name):
        app = self.apps['name']
        self.tabWidget.addTab(app, name)

    def close_app(self):
        current_tab = self.tabWidget

    def search(self):
        symbol = self.lineEdit_7.text()

    def select_timeframe(self):
        if self.radioButton.isChecked():
            self.comboBox_37.setEnabled(True)
            self.dateTimeEdit_3.setDisabled(True)
            self.dateTimeEdit_4.setDisabled(True)
        elif self.radioButton_2.isChecked():
            self.comboBox_37.setDisabled(True)
            self.dateTimeEdit_3.setEnabled(True)
            self.dateTimeEdit_4.setDisabled(True)
        else:
            self.comboBox_37.setDisabled(True)
            self.dateTimeEdit_3.setEnabled(True)
            self.dateTimeEdit_4.setEnabled(True)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "self"))
        self.groupBox_2.setTitle(_translate("self", "DATAZAUR"))
        self.groupBox_29.setTitle(_translate("self", "TIMEFRAME"))
        self.radioButton.setText(_translate("self", "LAST"))
        self.radioButton_2.setText(_translate("self", "SINCE"))
        self.comboBox_37.setItemText(0, _translate("self", "12h"))
        self.comboBox_37.setItemText(1, _translate("self", "24h"))
        self.comboBox_37.setItemText(2, _translate("self", "2d"))
        self.comboBox_37.setItemText(3, _translate("self", "3d"))
        self.comboBox_37.setItemText(4, _translate("self", "1w"))
        self.comboBox_37.setItemText(5, _translate("self", "2w"))
        self.comboBox_37.setItemText(6, _translate("self", "3w"))
        self.comboBox_37.setItemText(7, _translate("self", "1M"))
        self.comboBox_37.setItemText(8, _translate("self", "2M"))
        self.comboBox_37.setItemText(9, _translate("self", "3M"))
        self.comboBox_37.setItemText(10, _translate("self", "6M"))
        self.comboBox_37.setItemText(11, _translate("self", "1Y"))
        self.comboBox_37.setItemText(12, _translate("self", "2Y"))
        self.comboBox_37.setItemText(13, _translate("self", "3Y"))
        self.comboBox_37.setItemText(14, _translate("self", "5Y"))
        self.comboBox_37.setItemText(15, _translate("self", "10Y"))
        self.comboBox_37.setItemText(16, _translate("self", "ALL DATA"))
        self.radioButton_3.setText(_translate("self", "RANGE"))
        self.label.setText(_translate("self", "END"))
        self.label_2.setText(_translate("self", "START"))
        self.groupBox_24.setTitle(_translate("self", " SEARCH RESULTS: "))
        self.groupBox_8.setTitle(_translate("self", "SELECTED:  "))
        self.pushButton_6.setText(_translate("self", "CHART"))
        self.pushButton_48.setText(_translate("self", "WATCH"))
        self.pushButton_49.setText(_translate("self", "VARIABLES"))
        self.pushButton_50.setText(_translate("self", "TRADE"))
        self.pushButton_53.setText(_translate("self", "ALERT"))
        self.pushButton_80.setText(_translate("self", "QUOTE"))
        self.label_16.setText(_translate("self", "ACTIONS: "))
        self.pushButton_82.setText(_translate("self", "CALCULATE RETURN"))
        self.pushButton_81.setText(_translate("self", "SEARCH"))
        self.checkBox_4.setText(_translate("self", "FILTER:"))
        self.comboBox_36.setItemText(0, _translate("self", "CRYPTO"))
        self.comboBox_36.setItemText(1, _translate("self", "INDEXES"))
        self.comboBox_36.setItemText(2, _translate("self", "EQUITIES"))
        self.comboBox_36.setItemText(3, _translate("self", "COMMODITIES"))
        self.comboBox_36.setItemText(4, _translate("self", "FX"))
        self.comboBox_36.setItemText(5, _translate("self", "FIXED INCOME"))
        self.comboBox_36.setItemText(6, _translate("self", "MACRO"))
        self.comboBox_36.setItemText(7, _translate("self", "FUNDAMENTALS"))
        self.menuFile.setTitle(_translate("self", "File"))
        self.menuSave.setTitle(_translate("self", "Save..."))
        self.menuAlgorithm.setTitle(_translate("self", "Algorithm"))
        self.menuExchange.setTitle(_translate("self", "Exchange"))
        self.menuSettings.setTitle(_translate("self", "Settings"))
        self.menuTheme.setTitle(_translate("self", "Theme"))
        self.menuHelp.setTitle(_translate("self", "Help"))
        self.menuAnalysis.setTitle(_translate("self", "Analysis"))
        self.menuView.setTitle(_translate("self", "View"))
        self.actionSave_all.setText(_translate("self", "All Algorithms"))
        self.actionAll_exchanges.setText(_translate("self", "All Exchanges"))
        self.actionSave_all_2.setText(_translate("self", "Save all"))
        self.actionAccount.setText(_translate("self", "Account"))
        self.actionLog_out.setText(_translate("self", "Log out"))
        self.actionExit.setText(_translate("self", "Exit"))
        self.actionOpen.setText(_translate("self", "Open..."))
        self.actionCrypto.setText(_translate("self", "Crypto"))
        self.actionEquities.setText(_translate("self", "Equities"))
        self.actionIndexes.setText(_translate("self", "Indexes"))
        self.actionFX.setText(_translate("self", "FX"))
        self.actionMacro.setText(_translate("self", "Macro"))
        self.actionFundamentals.setText(_translate("self", "Fundamentals"))
        self.actionFixed_Income.setText(_translate("self", "Fixed Income"))
        self.actionCharts.setText(_translate("self", "Charts"))
        self.actionAlgorithm_Wizard.setText(_translate("self", "Algorithm Wizard"))
        self.actionPortfolio_Manager.setText(_translate("self", "Portfolio"))
        self.actionWatchlist.setText(_translate("self", "Watchlist"))
        self.actionMarket_Alerts.setText(_translate("self", "Alerts"))
        self.actionTwitter_Monitor.setText(_translate("self", "Twitter Monitor"))
        self.actionCurrency_Converter.setText(_translate("self", "FX Rates"))
        self.actionBacktest_Simulator.setText(_translate("self", "Backtest Simulator"))
        self.actionConfig.setText(_translate("self", "Settings"))
        self.actionPreferences.setText(_translate("self", "Preferences"))
        self.actionDatabase.setText(_translate("self", "Database"))
        self.actionDatazaur_Help.setText(_translate("self", "Datazaur Help..."))
        self.actionContribute.setText(_translate("self", "Contribute"))
        self.actionDonate.setText(_translate("self", "Donate"))
        self.actionAbout_Datazaur.setText(_translate("self", "About Datazaur"))
        self.actionDark_navy.setText(_translate("self", "Navy"))
        self.actionLight.setText(_translate("self", "Light"))
        self.actionCustom.setText(_translate("self", "Custom"))
        self.actionDatabase_2.setText(_translate("self", "Database"))
        self.actionEXPLORER.setText(_translate("self", "Explorer"))
        self.actionCrypto_Overview.setText(_translate("self", "Crypto Market Overview"))
        self.actionADF_Test.setText(_translate("self", "ADF-Test"))
        self.actionKPSS_Test.setText(_translate("self", "KPSS-Test"))
        self.actionEngle_Granger_Test.setText(_translate("self", "Engle-Granger Test"))
        self.actionBacktest.setText(_translate("self", "Backtest"))
        self.actionCrypto_Wallet.setText(_translate("self", "Crypto Wallet"))
        self.actionNews_Feed.setText(_translate("self", "News Feed"))
        self.actionCustom_Scripts.setText(_translate("self", "Custom Scripts"))
        self.actionMarkets.setText(_translate("self", "Markets"))
        self.actionTrading.setText(_translate("self", "Trading"))
        self.actionMatrix.setText(_translate("self", "Matrix"))
        self.actionMarkets_2.setText(_translate("self", "Markets"))
        self.actionTrading_2.setText(_translate("self", "Trading"))
        self.actionCharts_2.setText(_translate("self", "Charts"))
        self.actionWatchlist_2.setText(_translate("self", "Watchlist"))
        self.actionAlgorithm_Wizard_2.setText(_translate("self", "Algorithm Wizard"))
        self.actionNews_Feed_2.setText(_translate("self", "News Feed"))
        self.actionScript_Editor.setText(_translate("self", "Script Editor"))
        self.actionPortfolio_Manager_2.setText(_translate("self", "Portfolio Manager"))
        self.actionDatabase_3.setText(_translate("self", "Database"))
        self.actionDocs.setText(_translate("self", "Docs"))


