


from PyQt5 import QtCore, QtGui, QtWidgets


class NewsWidget(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.setObjectName("Form")
        self.resize(952, 662)
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(0, 0, 951, 661))
        self.widget.setObjectName("widget")
        self.pushButton_44 = QtWidgets.QPushButton(self.widget)
        self.pushButton_44.setGeometry(QtCore.QRect(350, 5, 76, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_78 = QtWidgets.QPushButton(self.widget)
        self.pushButton_78.setGeometry(QtCore.QRect(635, 5, 76, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_78.setFont(font)
        self.pushButton_78.setObjectName("pushButton_78")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_11.setGeometry(QtCore.QRect(810, 5, 131, 21))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.groupBox_20 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_20.setGeometry(QtCore.QRect(3, 3, 156, 651))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.groupBox_20.setFont(font)
        self.groupBox_20.setObjectName("groupBox_20")
        self.listWidget_8 = QtWidgets.QListWidget(self.groupBox_20)
        self.listWidget_8.setGeometry(QtCore.QRect(8, 90, 141, 556))
        self.listWidget_8.setObjectName("listWidget_8")
        self.pushButton_43 = QtWidgets.QPushButton(self.groupBox_20)
        self.pushButton_43.setGeometry(QtCore.QRect(128, 60, 21, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setAutoDefault(False)
        self.pushButton_43.setDefault(False)
        self.pushButton_43.setFlat(False)
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_42 = QtWidgets.QPushButton(self.groupBox_20)
        self.pushButton_42.setGeometry(QtCore.QRect(65, 60, 21, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setAutoDefault(False)
        self.pushButton_42.setDefault(False)
        self.pushButton_42.setObjectName("pushButton_42")
        self.label_18 = QtWidgets.QLabel(self.groupBox_20)
        self.label_18.setGeometry(QtCore.QRect(9, 30, 31, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.groupBox_20)
        self.lineEdit_13.setGeometry(QtCore.QRect(43, 30, 106, 21))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.toolButton = QtWidgets.QToolButton(self.groupBox_20)
        self.toolButton.setGeometry(QtCore.QRect(10, 60, 21, 21))
        self.toolButton.setAutoRaise(False)
        self.toolButton.setObjectName("toolButton")
        self.pushButton_47 = QtWidgets.QPushButton(self.widget)
        self.pushButton_47.setGeometry(QtCore.QRect(445, 5, 76, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_47.setFont(font)
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_46 = QtWidgets.QPushButton(self.widget)
        self.pushButton_46.setGeometry(QtCore.QRect(165, 5, 76, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_46.setFont(font)
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_45 = QtWidgets.QPushButton(self.widget)
        self.pushButton_45.setGeometry(QtCore.QRect(255, 5, 76, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_45.setFont(font)
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_71 = QtWidgets.QPushButton(self.widget)
        self.pushButton_71.setGeometry(QtCore.QRect(540, 5, 76, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_71.setFont(font)
        self.pushButton_71.setObjectName("pushButton_71")
        self.tableView_5 = QtWidgets.QTableView(self.widget)
        self.tableView_5.setGeometry(QtCore.QRect(165, 35, 776, 616))
        self.tableView_5.setObjectName("tableView_5")
        self.pushButton_79 = QtWidgets.QPushButton(self.widget)
        self.pushButton_79.setGeometry(QtCore.QRect(730, 5, 76, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.pushButton_79.setFont(font)
        self.pushButton_79.setObjectName("pushButton_79")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_44.setText(_translate("Form", "SAVE URLS"))
        self.pushButton_78.setText(_translate("Form", "REFRESH"))
        self.groupBox_20.setTitle(_translate("Form", "SOURCES"))
        self.pushButton_43.setText(_translate("Form", "X"))
        self.pushButton_42.setText(_translate("Form", "+"))
        self.label_18.setText(_translate("Form", "URL:"))
        self.toolButton.setText(_translate("Form", "..."))
        self.pushButton_47.setText(_translate("Form", "BOOKMARK"))
        self.pushButton_46.setText(_translate("Form", "SHARE"))
        self.pushButton_45.setText(_translate("Form", "COPY URL"))
        self.pushButton_71.setText(_translate("Form", "REFRESH"))
        self.pushButton_79.setText(_translate("Form", "OPEN"))


