

from PyQt5 import QtCore, QtGui, QtWidgets


class AlgorithmWidget(QtWidgets.QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.setObjectName("ALGORITHMS")
        self.resize(1074, 661)
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1071, 656))
        self.widget.setObjectName("widget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 75, 331, 316))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.tableView_10 = QtWidgets.QTableView(self.groupBox_3)
        self.tableView_10.setGeometry(QtCore.QRect(5, 30, 296, 206))
        self.tableView_10.setObjectName("tableView_10")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(135, 245, 191, 25))
        self.lineEdit_6.setClearButtonEnabled(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_48 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_48.setGeometry(QtCore.QRect(305, 55, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_48.setFont(font)
        self.pushButton_48.setStyleSheet("font: 63 10pt \"Ubuntu Bold\";")
        self.pushButton_48.setCheckable(True)
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_49 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_49.setGeometry(QtCore.QRect(305, 30, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_49.setFont(font)
        self.pushButton_49.setStyleSheet("font: 63 10pt \"Ubuntu Bold\";")
        self.pushButton_49.setObjectName("pushButton_49")
        self.pushButton_50 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_50.setGeometry(QtCore.QRect(305, 125, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_50.setFont(font)
        self.pushButton_50.setStyleSheet("font: 63 10pt \"Ubuntu Bold\";")
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_52 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_52.setGeometry(QtCore.QRect(305, 150, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_52.setFont(font)
        self.pushButton_52.setStyleSheet("font: 63 10pt \"Ubuntu Bold\";")
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_53 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_53.setGeometry(QtCore.QRect(305, 90, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_53.setFont(font)
        self.pushButton_53.setStyleSheet("font: 63 10pt \"Ubuntu Bold\";")
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_47 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_47.setGeometry(QtCore.QRect(305, 215, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Bold")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_47.setFont(font)
        self.pushButton_47.setStyleSheet("font: 63 13pt \"Ubuntu Bold\";")
        self.pushButton_47.setObjectName("pushButton_47")
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        self.label_33.setGeometry(QtCore.QRect(5, 245, 126, 25))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("font: 63 12pt \"FixedsysTTF\";")
        self.label_33.setObjectName("label_33")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_11.setGeometry(QtCore.QRect(230, 280, 96, 26))
        self.pushButton_11.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_54 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_54.setGeometry(QtCore.QRect(5, 280, 96, 26))
        self.pushButton_54.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_54.setObjectName("pushButton_54")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_10.setGeometry(QtCore.QRect(118, 280, 96, 26))
        self.pushButton_10.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_51 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_51.setGeometry(QtCore.QRect(305, 190, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_51.setFont(font)
        self.pushButton_51.setStyleSheet("font: 63 10pt \"Ubuntu Bold\";")
        self.pushButton_51.setObjectName("pushButton_51")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(5, 10, 131, 25))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_59 = QtWidgets.QPushButton(self.widget)
        self.pushButton_59.setGeometry(QtCore.QRect(235, 40, 96, 26))
        self.pushButton_59.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_59.setObjectName("pushButton_59")
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setGeometry(QtCore.QRect(0, 65, 336, 16))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.groupBox_18 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_18.setGeometry(QtCore.QRect(715, 255, 356, 221))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.groupBox_18.setFont(font)
        self.groupBox_18.setObjectName("groupBox_18")
        self.groupBox_16 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_16.setGeometry(QtCore.QRect(715, 0, 356, 251))
        self.groupBox_16.setObjectName("groupBox_16")
        self.groupBox_17 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_17.setGeometry(QtCore.QRect(5, 25, 213, 136))
        self.groupBox_17.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.groupBox_17.setObjectName("groupBox_17")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_17)
        self.formLayout.setContentsMargins(3, 3, 3, 3)
        self.formLayout.setObjectName("formLayout")
        self.label_44 = QtWidgets.QLabel(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("font: 63 10pt \"FixedsysTTF\";")
        self.label_44.setObjectName("label_44")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_44)
        self.comboBox_16 = QtWidgets.QComboBox(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.comboBox_16.setFont(font)
        self.comboBox_16.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.comboBox_16.setObjectName("comboBox_16")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_16)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setStyleSheet("font: 63 10pt \"FixedsysTTF\";")
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radioButton_6)
        self.comboBox_12 = QtWidgets.QComboBox(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.comboBox_12.setFont(font)
        self.comboBox_12.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.comboBox_12.setObjectName("comboBox_12")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_12)
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setStyleSheet("font: 63 10pt \"FixedsysTTF\";")
        self.radioButton_7.setObjectName("radioButton_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.radioButton_7)
        self.dateTimeEdit_3 = QtWidgets.QDateTimeEdit(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dateTimeEdit_3.setFont(font)
        self.dateTimeEdit_3.setStyleSheet("font: 10pt \"Ubuntu\";")
        self.dateTimeEdit_3.setObjectName("dateTimeEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit_3)
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setStyleSheet("font: 63 10pt \"FixedsysTTF\";")
        self.radioButton_8.setObjectName("radioButton_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.radioButton_8)
        self.dateTimeEdit_4 = QtWidgets.QDateTimeEdit(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dateTimeEdit_4.setFont(font)
        self.dateTimeEdit_4.setStyleSheet("font: 10pt \"Ubuntu\";")
        self.dateTimeEdit_4.setObjectName("dateTimeEdit_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateTimeEdit_4)
        self.groupBox_19 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_19.setGeometry(QtCore.QRect(220, 25, 131, 111))
        self.groupBox_19.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.groupBox_19.setObjectName("groupBox_19")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkBox_3.setGeometry(QtCore.QRect(5, 25, 46, 23))
        self.checkBox_3.setStyleSheet("font: 63 10pt \"FixedsysTTF\";")
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkBox_4.setGeometry(QtCore.QRect(70, 25, 56, 23))
        self.checkBox_4.setStyleSheet("font: 63 10pt \"FixedsysTTF\";")
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_19)
        self.checkBox_5.setGeometry(QtCore.QRect(5, 50, 61, 23))
        self.checkBox_5.setStyleSheet("font: 63 10pt \"FixedsysTTF\";")
        self.checkBox_5.setChecked(True)
        self.checkBox_5.setObjectName("checkBox_5")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_19)
        self.spinBox.setEnabled(True)
        self.spinBox.setGeometry(QtCore.QRect(70, 50, 56, 23))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("font: 10pt \"Ubuntu\";")
        self.spinBox.setMaximum(10)
        self.spinBox.setProperty("value", 2)
        self.spinBox.setObjectName("spinBox")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_19)
        self.pushButton_13.setGeometry(QtCore.QRect(70, 80, 56, 23))
        self.pushButton_13.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_13.setObjectName("pushButton_13")
        self.groupBox_20 = QtWidgets.QGroupBox(self.groupBox_16)
        self.groupBox_20.setGeometry(QtCore.QRect(220, 140, 131, 106))
        self.groupBox_20.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.groupBox_20.setObjectName("groupBox_20")
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox_20)
        self.pushButton_14.setGeometry(QtCore.QRect(70, 75, 56, 23))
        self.pushButton_14.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_14.setObjectName("pushButton_14")
        self.comboBox_17 = QtWidgets.QComboBox(self.groupBox_20)
        self.comboBox_17.setGeometry(QtCore.QRect(5, 45, 121, 25))
        self.comboBox_17.setStyleSheet("font: 63 10pt \"FixedsysTTF\";")
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.label_45 = QtWidgets.QLabel(self.groupBox_20)
        self.label_45.setGeometry(QtCore.QRect(5, 25, 36, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("font: 63 10pt \"FixedsysTTF\";")
        self.label_45.setObjectName("label_45")
        self.frame_17 = QtWidgets.QFrame(self.groupBox_16)
        self.frame_17.setGeometry(QtCore.QRect(5, 165, 131, 34))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_17)
        self.pushButton_15.setGeometry(QtCore.QRect(5, 5, 121, 23))
        self.pushButton_15.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_15.setObjectName("pushButton_15")
        self.frame_18 = QtWidgets.QFrame(self.groupBox_16)
        self.frame_18.setGeometry(QtCore.QRect(140, 165, 78, 34))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_16.setGeometry(QtCore.QRect(5, 5, 66, 23))
        self.pushButton_16.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_16.setObjectName("pushButton_16")
        self.frame_5 = QtWidgets.QFrame(self.widget)
        self.frame_5.setGeometry(QtCore.QRect(335, 0, 376, 481))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.frame_5.setFont(font)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.frame_5)
        self.tabWidget_5.setGeometry(QtCore.QRect(0, 0, 376, 271))
        self.tabWidget_5.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.frame_6 = QtWidgets.QFrame(self.tab_11)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 371, 236))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 3, 1, 1, 1)
        self.tabWidget_5.addTab(self.tab_11, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.frame_7 = QtWidgets.QFrame(self.tab_13)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 371, 236))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.comboBox_15 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_15.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_15, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_7)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_7)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 0, 1, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_2.addWidget(self.lineEdit_12, 1, 1, 1, 1)
        self.tabWidget_5.addTab(self.tab_13, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.frame_8 = QtWidgets.QFrame(self.tab_12)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 371, 236))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_3.addWidget(self.lineEdit_18, 2, 1, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_3.addWidget(self.lineEdit_17, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_8)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_8)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_8)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.comboBox_21 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.comboBox_21.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_21, 0, 1, 1, 1)
        self.tabWidget_5.addTab(self.tab_12, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.frame_9 = QtWidgets.QFrame(self.tab_14)
        self.frame_9.setGeometry(QtCore.QRect(0, 0, 371, 236))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_16 = QtWidgets.QLabel(self.frame_9)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 0, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_4.addWidget(self.lineEdit_19, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_9)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 1, 0, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_4.addWidget(self.lineEdit_20, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_9)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 2, 0, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_4.addWidget(self.lineEdit_21, 2, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_9)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 3, 0, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_4.addWidget(self.lineEdit_22, 3, 1, 1, 1)
        self.tabWidget_5.addTab(self.tab_14, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.frame_16 = QtWidgets.QFrame(self.tab_15)
        self.frame_16.setGeometry(QtCore.QRect(0, 0, 371, 236))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.tabWidget_5.addTab(self.tab_15, "")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_27.setGeometry(QtCore.QRect(189, 280, 177, 27))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.label_24 = QtWidgets.QLabel(self.frame_5)
        self.label_24.setGeometry(QtCore.QRect(15, 280, 168, 27))
        self.label_24.setObjectName("label_24")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_28.setGeometry(QtCore.QRect(189, 325, 177, 27))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_25 = QtWidgets.QLabel(self.frame_5)
        self.label_25.setGeometry(QtCore.QRect(15, 325, 168, 27))
        self.label_25.setObjectName("label_25")
        self.pushButton_57 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_57.setGeometry(QtCore.QRect(255, 450, 116, 26))
        self.pushButton_57.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_57.setObjectName("pushButton_57")
        self.label_26 = QtWidgets.QLabel(self.frame_5)
        self.label_26.setGeometry(QtCore.QRect(16, 370, 168, 27))
        self.label_26.setObjectName("label_26")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_29.setGeometry(QtCore.QRect(190, 370, 177, 27))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.label_27 = QtWidgets.QLabel(self.frame_5)
        self.label_27.setGeometry(QtCore.QRect(16, 415, 56, 27))
        self.label_27.setObjectName("label_27")
        self.comboBox_14 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_14.setGeometry(QtCore.QRect(190, 415, 121, 25))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.comboBox_14.addItem("")
        self.pushButton_71 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_71.setGeometry(QtCore.QRect(325, 415, 41, 26))
        self.pushButton_71.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_71.setObjectName("pushButton_71")
        self.comboBox_18 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_18.setGeometry(QtCore.QRect(75, 415, 101, 25))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.comboBox_18.addItem("")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(145, 10, 186, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.groupBox_9 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_9.setGeometry(QtCore.QRect(5, 450, 326, 206))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.groupBox_9.setFont(font)
        self.groupBox_9.setStyleSheet("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.tabWidget_9 = QtWidgets.QTabWidget(self.groupBox_9)
        self.tabWidget_9.setGeometry(QtCore.QRect(0, 25, 261, 177))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.tabWidget_9.setFont(font)
        self.tabWidget_9.setStyleSheet("font: 63 10pt \"FixedsysTTF\";")
        self.tabWidget_9.setObjectName("tabWidget_9")
        self.tab_30 = QtWidgets.QWidget()
        self.tab_30.setObjectName("tab_30")
        self.listWidget_9 = QtWidgets.QListWidget(self.tab_30)
        self.listWidget_9.setGeometry(QtCore.QRect(0, 0, 256, 146))
        self.listWidget_9.setObjectName("listWidget_9")
        self.tabWidget_9.addTab(self.tab_30, "")
        self.tab_31 = QtWidgets.QWidget()
        self.tab_31.setObjectName("tab_31")
        self.listWidget_10 = QtWidgets.QListWidget(self.tab_31)
        self.listWidget_10.setGeometry(QtCore.QRect(0, 0, 256, 146))
        self.listWidget_10.setObjectName("listWidget_10")
        self.tabWidget_9.addTab(self.tab_31, "")
        self.tab_32 = QtWidgets.QWidget()
        self.tab_32.setObjectName("tab_32")
        self.listWidget_11 = QtWidgets.QListWidget(self.tab_32)
        self.listWidget_11.setGeometry(QtCore.QRect(0, 0, 256, 146))
        self.listWidget_11.setObjectName("listWidget_11")
        self.tabWidget_9.addTab(self.tab_32, "")
        self.pushButton_62 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_62.setGeometry(QtCore.QRect(265, 50, 56, 26))
        self.pushButton_62.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_62.setObjectName("pushButton_62")
        self.pushButton_63 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_63.setGeometry(QtCore.QRect(265, 80, 56, 26))
        self.pushButton_63.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_63.setObjectName("pushButton_63")
        self.pushButton_64 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_64.setGeometry(QtCore.QRect(265, 170, 56, 26))
        self.pushButton_64.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_64.setObjectName("pushButton_64")
        self.pushButton_65 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_65.setGeometry(QtCore.QRect(265, 110, 56, 26))
        self.pushButton_65.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_65.setObjectName("pushButton_65")

        self.retranslateUi()
        self.tabWidget_5.setCurrentIndex(3)
        self.tabWidget_9.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_3.setTitle(_translate("Form", " VARIABLES"))
        self.pushButton_48.setText(_translate("Form", "C"))
        self.pushButton_49.setText(_translate("Form", "Y"))
        self.pushButton_50.setText(_translate("Form", "d"))
        self.pushButton_52.setText(_translate("Form", "ln"))
        self.pushButton_53.setText(_translate("Form", "i"))
        self.pushButton_47.setText(_translate("Form", "+"))
        self.label_33.setText(_translate("Form", "CUSTOM FORMULA"))
        self.pushButton_11.setText(_translate("Form", "SAVE"))
        self.pushButton_54.setText(_translate("Form", "CLEAR"))
        self.pushButton_10.setText(_translate("Form", "LOAD"))
        self.pushButton_51.setText(_translate("Form", "X"))
        self.label_3.setText(_translate("Form", "ALGORITHM NAME"))
        self.pushButton_59.setText(_translate("Form", "SAVE"))
        self.groupBox_18.setTitle(_translate("Form", " TESTS"))
        self.groupBox_16.setTitle(_translate("Form", " TESTS"))
        self.groupBox_17.setTitle(_translate("Form", " TIMEFRAME"))
        self.label_44.setText(_translate("Form", "  INTERVAL"))
        self.radioButton_6.setText(_translate("Form", "LAST"))
        self.radioButton_7.setText(_translate("Form", "SINCE"))
        self.radioButton_8.setText(_translate("Form", "RANGE"))
        self.groupBox_19.setTitle(_translate("Form", "STATIONARITY"))
        self.checkBox_3.setText(_translate("Form", "ADF"))
        self.checkBox_4.setText(_translate("Form", "KPSS"))
        self.checkBox_5.setText(_translate("Form", "DIFFS"))
        self.pushButton_13.setText(_translate("Form", "RUN"))
        self.groupBox_20.setTitle(_translate("Form", "COINTEGRATION"))
        self.pushButton_14.setText(_translate("Form", "RUN"))
        self.comboBox_17.setItemText(0, _translate("Form", "Engle-Granger"))
        self.comboBox_17.setItemText(1, _translate("Form", "Johansen"))
        self.label_45.setText(_translate("Form", "TEST"))
        self.pushButton_15.setText(_translate("Form", "BACKTEST"))
        self.pushButton_16.setText(_translate("Form", "CONFIG"))
        self.label_4.setText(_translate("Form", "ENTRY Z-SCORE"))
        self.label_5.setText(_translate("Form", "TAKE PROFIT Z-SCORE"))
        self.label_6.setText(_translate("Form", "STOP LOSS Z-SCORE"))
        self.label_7.setText(_translate("Form", "TextLabel"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_11), _translate("Form", "COINT"))
        self.label_8.setText(_translate("Form", "MA1 (SHORT)"))
        self.comboBox_15.setItemText(0, _translate("Form", "GOLDEN CROSS"))
        self.comboBox_15.setItemText(1, _translate("Form", "DEATH CROSS"))
        self.label_9.setText(_translate("Form", "MA2 (LONG)"))
        self.label_10.setText(_translate("Form", "SIGNAL"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_13), _translate("Form", "MA"))
        self.label_12.setText(_translate("Form", "INDICATOR"))
        self.label_15.setText(_translate("Form", "TextLabel"))
        self.label_14.setText(_translate("Form", "STOP LOSS Z-SCORE"))
        self.comboBox_21.setItemText(0, _translate("Form", "MACD"))
        self.comboBox_21.setItemText(1, _translate("Form", "RSI"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_12), _translate("Form", "TA"))
        self.label_16.setText(_translate("Form", "PROFILE"))
        self.label_17.setText(_translate("Form", "KEYWORD"))
        self.label_18.setText(_translate("Form", "STOP LOSS Z-SCORE"))
        self.label_19.setText(_translate("Form", "TextLabel"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_14), _translate("Form", "TWITTER"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_15), _translate("Form", "SCRIPT"))
        self.label_24.setText(_translate("Form", "TAKE PROFIT"))
        self.label_25.setText(_translate("Form", "STOP LOSS"))
        self.pushButton_57.setText(_translate("Form", "SAVE CONFIG"))
        self.label_26.setText(_translate("Form", "STOP ALGORITHM"))
        self.label_27.setText(_translate("Form", "ALERT"))
        self.comboBox_14.setItemText(0, _translate("Form", "ALL TRADES"))
        self.comboBox_14.setItemText(1, _translate("Form", "OPENED POSITION"))
        self.comboBox_14.setItemText(2, _translate("Form", "TAKE PROFIT"))
        self.comboBox_14.setItemText(3, _translate("Form", "STOP LOSS"))
        self.comboBox_14.setItemText(4, _translate("Form", "STOP ALGORITHM"))
        self.pushButton_71.setText(_translate("Form", "ADD"))
        self.comboBox_18.setItemText(0, _translate("Form", "TELEGRAM"))
        self.comboBox_18.setItemText(1, _translate("Form", "EMAIL"))
        self.comboBox_18.setItemText(2, _translate("Form", "SMS"))
        self.groupBox_9.setTitle(_translate("Form", " DATABASE "))
        self.tabWidget_9.setTabText(self.tabWidget_9.indexOf(self.tab_30), _translate("Form", "ALGORITHMS"))
        self.tabWidget_9.setTabText(self.tabWidget_9.indexOf(self.tab_31), _translate("Form", "VARIABLES"))
        self.tabWidget_9.setTabText(self.tabWidget_9.indexOf(self.tab_32), _translate("Form", "CONFIGS"))
        self.pushButton_62.setText(_translate("Form", "SAVE"))
        self.pushButton_63.setText(_translate("Form", "LOAD"))
        self.pushButton_64.setText(_translate("Form", "DELETE"))
        self.pushButton_65.setText(_translate("Form", "INFO"))



