


from PyQt5 import QtCore, QtGui, QtWidgets

from investpy import economic_calendar
from .pandasmodel import PandasModel


class CalendarWidget(QtWidgets.QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.setObjectName("CALENDAR")
        self.resize(1078, 654)
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1071, 651))
        self.widget.setObjectName("widget")
        self.line_5 = QtWidgets.QFrame(self.widget)
        self.line_5.setGeometry(QtCore.QRect(200, 0, 10, 41))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.line_5.setFont(font)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.comboBox_8 = QtWidgets.QComboBox(self.widget)
        self.comboBox_8.setGeometry(QtCore.QRect(665, 7, 111, 26))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.comboBox_8.setFont(font)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.line_6 = QtWidgets.QFrame(self.widget)
        self.line_6.setGeometry(QtCore.QRect(415, 0, 10, 41))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.line_6.setFont(font)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_37 = QtWidgets.QLabel(self.widget)
        self.label_37.setGeometry(QtCore.QRect(210, 7, 81, 26))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.line_8 = QtWidgets.QFrame(self.widget)
        self.line_8.setGeometry(QtCore.QRect(880, 0, 10, 41))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.line_8.setFont(font)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.comboBox_7 = QtWidgets.QComboBox(self.widget)
        self.comboBox_7.setGeometry(QtCore.QRect(525, 7, 111, 26))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.comboBox_7.setFont(font)
        self.comboBox_7.setObjectName("comboBox_7")
        self.label_36 = QtWidgets.QLabel(self.widget)
        self.label_36.setGeometry(QtCore.QRect(5, 7, 61, 26))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("")
        self.label_36.setObjectName("label_36")
        self.label_38 = QtWidgets.QLabel(self.widget)
        self.label_38.setGeometry(QtCore.QRect(425, 7, 96, 26))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_37.setGeometry(QtCore.QRect(895, 7, 173, 26))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.lineEdit_37.setFont(font)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.pushButton_31 = QtWidgets.QPushButton(self.widget)
        self.pushButton_31.setGeometry(QtCore.QRect(785, 7, 91, 26))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_31.setObjectName("pushButton_31")
        self.comboBox_5 = QtWidgets.QComboBox(self.widget)
        self.comboBox_5.setGeometry(QtCore.QRect(75, 7, 111, 26))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.comboBox_5.setFont(font)
        self.comboBox_5.setStyleSheet("")
        self.comboBox_5.setObjectName("comboBox_5")
        self.tableView_12 = QtWidgets.QTableView(self.widget)
        self.tableView_12.setGeometry(QtCore.QRect(-1, 40, 1069, 608))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.tableView_12.setFont(font)
        self.tableView_12.setObjectName("tableView_12")
        self.tableView_12.setStyleSheet("font: 32 11pt \"Ubuntu\"")
        self.comboBox_6 = QtWidgets.QComboBox(self.widget)
        self.comboBox_6.setGeometry(QtCore.QRect(290, 7, 111, 26))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.comboBox_6.setFont(font)
        self.comboBox_6.setObjectName("comboBox_6")
        self.line_7 = QtWidgets.QFrame(self.widget)
        self.line_7.setGeometry(QtCore.QRect(650, 0, 10, 41))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.line_7.setFont(font)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.setup_calendar()

    def setup_calendar(self):
        self.tableView_12.setModel(PandasModel(economic_calendar()))


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.comboBox_8.setItemText(0, _translate("Form", "Telegram"))
        self.comboBox_8.setItemText(1, _translate("Form", "email"))
        self.comboBox_8.setItemText(2, _translate("Form", "SMS"))
        self.label_37.setText(_translate("Form", "CURRENCY"))
        self.label_36.setText(_translate("Form", "COUNTRY"))
        self.label_38.setText(_translate("Form", "IMPORTANCE"))
        self.pushButton_31.setText(_translate("Form", "SET ALERT"))

