


from PyQt5 import QtCore, QtGui, QtWidgets



class EditorWidget(QtWidgets.QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.setObjectName("EDITOR")
        self.resize(1080, 660)
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1081, 661))
        self.widget.setObjectName("widget")
        self.pushButton_40 = QtWidgets.QPushButton(self.widget)
        self.pushButton_40.setGeometry(QtCore.QRect(5, 415, 81, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_40.setFont(font)
        self.pushButton_40.setStyleSheet("font: 63 12pt \"FixedsysTTF\";")
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_44 = QtWidgets.QPushButton(self.widget)
        self.pushButton_44.setGeometry(QtCore.QRect(80, 5, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Bold")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setStyleSheet("font: 63 13pt \"Ubuntu Bold\";")
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(95, 450, 81, 31))
        self.pushButton_2.setStyleSheet("font: 63 12pt \"FixedsysTTF\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(5, 5, 66, 17))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setGeometry(QtCore.QRect(5, 32, 171, 379))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(95, 415, 81, 31))
        self.pushButton_4.setStyleSheet("font: 63 12pt \"FixedsysTTF\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.widget)
        self.tabWidget_2.setGeometry(QtCore.QRect(180, 0, 896, 655))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setStyleSheet("font: 63 12pt \"FixedsysTTF\";")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_9)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 0, 891, 621))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.pushButton_42 = QtWidgets.QPushButton(self.widget)
        self.pushButton_42.setGeometry(QtCore.QRect(155, 5, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setStyleSheet("font: 63 10pt \"Ubuntu Bold\";")
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_43 = QtWidgets.QPushButton(self.widget)
        self.pushButton_43.setGeometry(QtCore.QRect(105, 5, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Bold")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setStyleSheet("font: 63 13pt \"Ubuntu Bold\";")
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_41 = QtWidgets.QPushButton(self.widget)
        self.pushButton_41.setGeometry(QtCore.QRect(130, 5, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Bold")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_41.setFont(font)
        self.pushButton_41.setStyleSheet("font: 63 13pt \"Ubuntu Bold\";")
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(5, 450, 81, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("font: 63 12pt \"FixedsysTTF\";")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi()
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)


    def new_file(self):
        pass

    def open_file(self):
        pass

    def save_file(self):
        pass

    def delete_file(self):
        pass

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_40.setText(_translate("Form", "OPEN"))
        self.pushButton_44.setText(_translate("Form", "+"))
        self.pushButton_2.setText(_translate("Form", "SAVE"))
        self.label_2.setText(_translate("Form", "SCRIPTS"))
        self.pushButton_4.setText(_translate("Form", "NEW"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("Form", "Untitled Document"))
        self.pushButton_42.setText(_translate("Form", "X"))
        self.pushButton_43.setText(_translate("Form", "+"))
        self.pushButton_41.setText(_translate("Form", "+"))
        self.pushButton_3.setText(_translate("Form", "DELETE"))

