

from PyQt5 import QtCore, QtGui, QtWidgets


class ExplorerWidget(QtWidgets.QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.setObjectName("EXPLORER")
        self.resize(1080, 659)
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1076, 656))
        self.widget.setObjectName("widget")
        self.frame_4 = QtWidgets.QFrame(self.widget)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1076, 654))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.groupBox_11 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_11.setGeometry(QtCore.QRect(240, 5, 731, 151))
        self.groupBox_11.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.groupBox_11.setObjectName("groupBox_11")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_11)
        self.textBrowser.setGeometry(QtCore.QRect(5, 25, 721, 121))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_12 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_12.setGeometry(QtCore.QRect(0, 5, 236, 646))
        self.groupBox_12.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.groupBox_12.setObjectName("groupBox_12")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_12)
        self.comboBox_2.setGeometry(QtCore.QRect(115, 30, 116, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox.setGeometry(QtCore.QRect(10, 30, 81, 26))
        self.checkBox.setObjectName("checkBox")
        self.comboBox_11 = QtWidgets.QComboBox(self.groupBox_12)
        self.comboBox_11.setGeometry(QtCore.QRect(115, 65, 116, 26))
        self.comboBox_11.setObjectName("comboBox_11")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 65, 96, 26))
        self.checkBox_2.setObjectName("checkBox_2")
        self.listWidget_6 = QtWidgets.QListWidget(self.groupBox_12)
        self.listWidget_6.setGeometry(QtCore.QRect(5, 145, 226, 496))
        self.listWidget_6.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_6.setObjectName("listWidget_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_2.setGeometry(QtCore.QRect(115, 115, 116, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.groupBox_21 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_21.setGeometry(QtCore.QRect(240, 160, 836, 491))
        self.groupBox_21.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.groupBox_21.setObjectName("groupBox_21")
        self.tableView_2 = QtWidgets.QTableView(self.groupBox_21)
        self.tableView_2.setGeometry(QtCore.QRect(5, 25, 826, 461))
        self.tableView_2.setObjectName("tableView_2")
        self.frame_20 = QtWidgets.QFrame(self.frame_4)
        self.frame_20.setGeometry(QtCore.QRect(975, 27, 96, 146))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.pushButton_70 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_70.setGeometry(QtCore.QRect(5, 110, 86, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.pushButton_70.setFont(font)
        self.pushButton_70.setStyleSheet("font: 32 13pt \"FixedsysTTF\";")
        self.pushButton_70.setObjectName("pushButton_70")
        self.pushButton_72 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_72.setGeometry(QtCore.QRect(5, 70, 86, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.pushButton_72.setFont(font)
        self.pushButton_72.setStyleSheet("font: 32 13pt \"FixedsysTTF\";")
        self.pushButton_72.setObjectName("pushButton_72")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_11.setTitle(_translate("Form", " DESCRIPTION"))
        self.groupBox_12.setTitle(_translate("Form", " SEARCH"))
        self.checkBox.setText(_translate("Form", "SOURCE"))
        self.checkBox_2.setText(_translate("Form", "CATEGORY"))
        self.groupBox_21.setTitle(_translate("Form", " SEARCH RESULTS"))
        self.pushButton_70.setText(_translate("Form", "CHART"))
        self.pushButton_72.setText(_translate("Form", "COMPARE"))

