

from PyQt5 import QtCore, QtGui, QtWidgets
import investpy
from .pandasmodel import PandasModel

class MonitorWidget(QtWidgets.QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.setObjectName("MONITOR")
        self.resize(1082, 664)
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1081, 661))
        self.widget.setObjectName("widget")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.widget)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 3, 1077, 656))
        self.tabWidget_4.setStyleSheet("font: 63 12pt \"FixedsysTTF\";")
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_16)
        self.comboBox_4.setGeometry(QtCore.QRect(80, 5, 96, 25))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_6 = QtWidgets.QLabel(self.tab_16)
        self.label_6.setGeometry(QtCore.QRect(10, 5, 66, 25))
        self.label_6.setObjectName("label_6")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_16)
        self.comboBox_5.setGeometry(QtCore.QRect(300, 5, 86, 25))
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_7 = QtWidgets.QLabel(self.tab_16)
        self.label_7.setGeometry(QtCore.QRect(220, 5, 76, 25))
        self.label_7.setObjectName("label_7")
        self.frame = QtWidgets.QFrame(self.tab_16)
        self.frame.setGeometry(QtCore.QRect(0, 35, 1076, 586))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_8.setEnabled(True)
        self.groupBox_8.setGeometry(QtCore.QRect(860, 5, 216, 576))
        self.groupBox_8.setMinimumSize(QtCore.QSize(216, 260))
        self.groupBox_8.setMaximumSize(QtCore.QSize(216, 600))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("font: 63 13pt \"FixedsysTTF\";")
        self.groupBox_8.setObjectName("groupBox_8")
        self.tableView_6 = QtWidgets.QTableView(self.groupBox_8)
        self.tableView_6.setGeometry(QtCore.QRect(5, 25, 206, 546))
        self.tableView_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_6.setObjectName("tableView_6")
        self.tableView_6.horizontalHeader().setVisible(False)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_5.setGeometry(QtCore.QRect(160, 0, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("font: 63 10pt \"FixedsysTTF\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_7.setGeometry(QtCore.QRect(645, 5, 216, 576))
        self.groupBox_7.setMinimumSize(QtCore.QSize(216, 260))
        self.groupBox_7.setMaximumSize(QtCore.QSize(216, 600))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.tableView_4 = QtWidgets.QTableView(self.groupBox_7)
        self.tableView_4.setGeometry(QtCore.QRect(5, 25, 206, 546))
        self.tableView_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_4.setObjectName("tableView_4")
        self.tableView_4.horizontalHeader().setVisible(False)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 0, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("font: 63 10pt \"FixedsysTTF\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 5, 216, 576))
        self.groupBox_4.setMinimumSize(QtCore.QSize(216, 260))
        self.groupBox_4.setMaximumSize(QtCore.QSize(216, 650))
        self.groupBox_4.setSizeIncrement(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.tableView_19 = QtWidgets.QTableView(self.groupBox_4)
        self.tableView_19.setGeometry(QtCore.QRect(5, 25, 206, 546))
        self.tableView_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_19.setObjectName("tableView_19")
        self.tableView_19.horizontalHeader().setVisible(False)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton.setGeometry(QtCore.QRect(160, 0, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("font: 63 10pt \"FixedsysTTF\";")
        self.pushButton.setObjectName("pushButton")
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_6.setGeometry(QtCore.QRect(430, 5, 216, 576))
        self.groupBox_6.setMinimumSize(QtCore.QSize(216, 260))
        self.groupBox_6.setMaximumSize(QtCore.QSize(216, 600))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.tableView_5 = QtWidgets.QTableView(self.groupBox_6)
        self.tableView_5.setGeometry(QtCore.QRect(5, 25, 206, 546))
        self.tableView_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_5.setObjectName("tableView_5")
        self.tableView_5.horizontalHeader().setVisible(False)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 0, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("font: 63 10pt \"FixedsysTTF\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_5.setGeometry(QtCore.QRect(215, 5, 216, 576))
        self.groupBox_5.setMinimumSize(QtCore.QSize(216, 260))
        self.groupBox_5.setMaximumSize(QtCore.QSize(216, 600))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.tableView_3 = QtWidgets.QTableView(self.groupBox_5)
        self.tableView_3.setGeometry(QtCore.QRect(5, 25, 206, 546))
        self.tableView_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_3.setObjectName("tableView_3")
        self.tableView_3.horizontalHeader().setVisible(False)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 0, 51, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("font: 63 10pt \"FixedsysTTF\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab_16)
        self.comboBox_6.setGeometry(QtCore.QRect(980, 5, 86, 25))
        self.comboBox_6.setObjectName("comboBox_6")
        self.label_8 = QtWidgets.QLabel(self.tab_16)
        self.label_8.setGeometry(QtCore.QRect(840, 5, 136, 25))
        self.label_8.setObjectName("label_8")
        self.tabWidget_4.addTab(self.tab_16, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.tabWidget_10 = QtWidgets.QTabWidget(self.tab_18)
        self.tabWidget_10.setGeometry(QtCore.QRect(0, 0, 1071, 621))
        self.tabWidget_10.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.tabWidget_10.setObjectName("tabWidget_10")
        self.tab_33 = QtWidgets.QWidget()
        self.tab_33.setObjectName("tab_33")
        self.tableView = QtWidgets.QTableView(self.tab_33)
        self.tableView.setGeometry(QtCore.QRect(3, 4, 1061, 581))
        self.tableView.setObjectName("tableView")
        self.tabWidget_10.addTab(self.tab_33, "")
        self.tab_34 = QtWidgets.QWidget()
        self.tab_34.setObjectName("tab_34")
        self.tableView_31 = QtWidgets.QTableView(self.tab_34)
        self.tableView_31.setGeometry(QtCore.QRect(3, 4, 1061, 581))
        self.tableView_31.setObjectName("tableView_31")
        self.tabWidget_10.addTab(self.tab_34, "")
        self.tab_35 = QtWidgets.QWidget()
        self.tab_35.setObjectName("tab_35")
        self.tableView_32 = QtWidgets.QTableView(self.tab_35)
        self.tableView_32.setGeometry(QtCore.QRect(3, 4, 1061, 581))
        self.tableView_32.setObjectName("tableView_32")
        self.tabWidget_10.addTab(self.tab_35, "")
        self.tabWidget_4.addTab(self.tab_18, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.tableView_7 = QtWidgets.QTableView(self.tab_19)
        self.tableView_7.setGeometry(QtCore.QRect(3, 4, 1067, 614))
        self.tableView_7.setObjectName("tableView_7")
        self.tabWidget_4.addTab(self.tab_19, "")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.tableView_13 = QtWidgets.QTableView(self.tab_20)
        self.tableView_13.setGeometry(QtCore.QRect(3, 4, 1068, 614))
        self.tableView_13.setObjectName("tableView_13")
        self.tabWidget_4.addTab(self.tab_20, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.tableView_14 = QtWidgets.QTableView(self.tab_21)
        self.tableView_14.setGeometry(QtCore.QRect(3, 4, 1068, 614))
        self.tableView_14.setObjectName("tableView_14")
        self.tabWidget_4.addTab(self.tab_21, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableView_2 = QtWidgets.QTableView(self.tab)
        self.tableView_2.setGeometry(QtCore.QRect(5, 40, 1066, 581))
        self.tableView_2.setObjectName("tableView_2")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.tab)
        self.dateTimeEdit.setGeometry(QtCore.QRect(903, 5, 166, 26))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(735, 5, 166, 26))
        self.checkBox.setObjectName("checkBox")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 5, 67, 26))
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(180, 5, 66, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab)
        self.comboBox_3.setGeometry(QtCore.QRect(275, 5, 66, 26))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(250, 5, 26, 26))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(80, 5, 91, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(345, 5, 21, 26))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 63 15pt \"FixedsysTTF\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(365, 5, 146, 26))
        self.label_5.setObjectName("label_5")
        self.tabWidget_4.addTab(self.tab, "")
        self.tab_23 = QtWidgets.QWidget()
        self.tab_23.setObjectName("tab_23")
        self.tableView_16 = QtWidgets.QTableView(self.tab_23)
        self.tableView_16.setGeometry(QtCore.QRect(3, 37, 1068, 581))
        self.tableView_16.setObjectName("tableView_16")
        self.comboBox = QtWidgets.QComboBox(self.tab_23)
        self.comboBox.setGeometry(QtCore.QRect(950, 5, 121, 25))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.tab_23)
        self.label.setGeometry(QtCore.QRect(895, 10, 51, 16))
        self.label.setObjectName("label")
        self.tabWidget_4.addTab(self.tab_23, "")
        self.tab_24 = QtWidgets.QWidget()
        self.tab_24.setObjectName("tab_24")
        self.tableView_17 = QtWidgets.QTableView(self.tab_24)
        self.tableView_17.setGeometry(QtCore.QRect(3, 4, 1068, 614))
        self.tableView_17.setObjectName("tableView_17")
        self.tabWidget_4.addTab(self.tab_24, "")
        self.tab_25 = QtWidgets.QWidget()
        self.tab_25.setObjectName("tab_25")
        self.tableView_18 = QtWidgets.QTableView(self.tab_25)
        self.tableView_18.setGeometry(QtCore.QRect(3, 4, 1068, 614))
        self.tableView_18.setObjectName("tableView_18")
        self.tabWidget_4.addTab(self.tab_25, "")
        self.tab_22 = QtWidgets.QWidget()
        self.tab_22.setObjectName("tab_22")
        self.tableView_15 = QtWidgets.QTableView(self.tab_22)
        self.tableView_15.setGeometry(QtCore.QRect(3, 4, 1068, 614))
        self.tableView_15.setObjectName("tableView_15")
        self.tabWidget_4.addTab(self.tab_22, "")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_36.setGeometry(QtCore.QRect(910, 5, 166, 26))
        self.lineEdit_36.setObjectName("lineEdit_36")

        self.retranslateUi()
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_10.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

        self.country = 'united states'
        self.group = 'metals'

        self.display_markets()

    def display_crypto(self):
        self.coins = investpy.get_cryptos_overview()
        #self.coins_info = investpy.get_crypto_information()
        self.tableView.setModel(PandasModel(self.coins))
        #self.tableView_31.setModel(PandasModel(self.coins))

    def display_stocks(self):
        self.stocks = investpy.stocks.get_stocks_overview(self.country)
        self.tableView_7.setModel(PandasModel(self.stocks))

    def display_indexes(self):
        self.indexes = investpy.get_indices_overview(self.country)
        self.tableView_13.setModel(PandasModel(self.indexes))

    def display_bonds(self):
        self.bonds = investpy.get_bonds_overview(self.country)
        self.tableView_14.setModel(PandasModel(self.bonds))

    def display_certificates(self):
        self.certificates = investpy.get_certificates_overview(self.country)
        self.tableView_15.setModel(PandasModel(self.certificates))

    def display_commodities(self):
        self.commodities = investpy.get_commodities_overview(self.group)
        self.tableView_16.setModel(PandasModel(self.commodities))

    def display_etfs(self):
        self.etfs = investpy.get_etfs_overview(self.country)
        self.tableView_17.setModel(PandasModel(self.etfs))

    def display_funds(self):
        self.funds = investpy.get_funds_overview(self.country)
        self.tableView_18.setModel(PandasModel(self.funds))


    def display_markets(self):
        for func in [self.display_crypto, self.display_stocks, self.display_bonds, self.display_etfs,
                     self.display_funds, self.display_commodities, self.display_certificates, self.display_indexes]:
            try:
                func()
            except:
                pass

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "country"))
        self.label_7.setText(_translate("Form", "currency"))
        self.groupBox_8.setTitle(_translate("Form", " COMMODITIES   "))
        self.pushButton_5.setText(_translate("Form", "change"))
        self.groupBox_7.setTitle(_translate("Form", " BONDS  "))
        self.pushButton_4.setText(_translate("Form", "change"))
        self.groupBox_4.setTitle(_translate("Form", " CRYPTO     "))
        self.pushButton.setText(_translate("Form", "change"))
        self.groupBox_6.setTitle(_translate("Form", " FOREX    "))
        self.pushButton_3.setText(_translate("Form", "change"))
        self.groupBox_5.setTitle(_translate("Form", " INDEXES      "))
        self.pushButton_2.setText(_translate("Form", "change"))
        self.label_8.setText(_translate("Form", "commodity group"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_16), _translate("Form", "MIX"))
        self.tabWidget_10.setTabText(self.tabWidget_10.indexOf(self.tab_33), _translate("Form", "PRICES"))
        self.tabWidget_10.setTabText(self.tabWidget_10.indexOf(self.tab_34), _translate("Form", "INFO"))
        self.tabWidget_10.setTabText(self.tabWidget_10.indexOf(self.tab_35), _translate("Form", "GLOBAL METRICS"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_18), _translate("Form", "CRYPTO"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_19), _translate("Form", "STOCKS"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_20), _translate("Form", "INDEXES"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_21), _translate("Form", "BONDS"))
        self.checkBox.setText(_translate("Form", "historical rates"))
        self.label_2.setText(_translate("Form", "convert"))
        self.label_3.setText(_translate("Form", "to"))
        self.label_4.setText(_translate("Form", "="))
        self.label_5.setText(_translate("Form", "TextLabel"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab), _translate("Form", "FOREX"))
        self.label.setText(_translate("Form", "group"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_23), _translate("Form", "COMMODITIES"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_24), _translate("Form", "ETFs"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_25), _translate("Form", "FUNDS"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_22), _translate("Form", "CERTIFICATES"))


