

from PyQt5 import QtCore, QtGui, QtWidgets
import investpy
from .pandasmodel import PandasModel

class MonitorWidget(QtWidgets.QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.setObjectName("MONITOR")
        self.resize(1082, 664)
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1081, 661))
        self.widget.setObjectName("widget")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.widget)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 3, 1077, 656))
        self.tabWidget_4.setStyleSheet("font: 63 12pt \"FixedsysTTF\";")
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_16)
        self.groupBox_8.setEnabled(True)
        self.groupBox_8.setGeometry(QtCore.QRect(860, 5, 216, 536))
        self.groupBox_8.setMinimumSize(QtCore.QSize(216, 260))
        self.groupBox_8.setMaximumSize(QtCore.QSize(216, 600))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet("font: 63 13pt \"FixedsysTTF\";")
        self.groupBox_8.setObjectName("groupBox_8")
        self.tableView_6 = QtWidgets.QTableView(self.groupBox_8)
        self.tableView_6.setGeometry(QtCore.QRect(5, 25, 206, 506))
        self.tableView_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_6.setObjectName("tableView_6")
        self.tableView_6.horizontalHeader().setVisible(False)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_16)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 5, 216, 536))
        self.groupBox_4.setMinimumSize(QtCore.QSize(216, 260))
        self.groupBox_4.setMaximumSize(QtCore.QSize(216, 600))
        self.groupBox_4.setSizeIncrement(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.tableView_19 = QtWidgets.QTableView(self.groupBox_4)
        self.tableView_19.setGeometry(QtCore.QRect(5, 25, 206, 506))
        self.tableView_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_19.setObjectName("tableView_19")
        self.tableView_19.horizontalHeader().setVisible(False)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_16)
        self.groupBox_6.setGeometry(QtCore.QRect(430, 5, 216, 536))
        self.groupBox_6.setMinimumSize(QtCore.QSize(216, 260))
        self.groupBox_6.setMaximumSize(QtCore.QSize(216, 600))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.tableView_5 = QtWidgets.QTableView(self.groupBox_6)
        self.tableView_5.setGeometry(QtCore.QRect(5, 25, 206, 506))
        self.tableView_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_5.setObjectName("tableView_5")
        self.tableView_5.horizontalHeader().setVisible(False)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_16)
        self.groupBox_5.setGeometry(QtCore.QRect(215, 5, 216, 536))
        self.groupBox_5.setMinimumSize(QtCore.QSize(216, 260))
        self.groupBox_5.setMaximumSize(QtCore.QSize(216, 600))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.tableView_3 = QtWidgets.QTableView(self.groupBox_5)
        self.tableView_3.setGeometry(QtCore.QRect(5, 25, 206, 506))
        self.tableView_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_3.setObjectName("tableView_3")
        self.tableView_3.horizontalHeader().setVisible(False)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_16)
        self.groupBox_7.setGeometry(QtCore.QRect(645, 5, 216, 536))
        self.groupBox_7.setMinimumSize(QtCore.QSize(216, 260))
        self.groupBox_7.setMaximumSize(QtCore.QSize(216, 600))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.tableView_4 = QtWidgets.QTableView(self.groupBox_7)
        self.tableView_4.setGeometry(QtCore.QRect(5, 25, 206, 506))
        self.tableView_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_4.setObjectName("tableView_4")
        self.tableView_4.horizontalHeader().setVisible(False)
        self.tabWidget_4.addTab(self.tab_16, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.tabWidget_10 = QtWidgets.QTabWidget(self.tab_18)
        self.tabWidget_10.setGeometry(QtCore.QRect(0, 0, 1071, 621))
        self.tabWidget_10.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.tabWidget_10.setObjectName("tabWidget_10")
        self.tab_33 = QtWidgets.QWidget()
        self.tab_33.setObjectName("tab_33")
        self.tableView = QtWidgets.QTableView(self.tab_33)
        self.tableView.setGeometry(QtCore.QRect(3, 4, 1061, 581))
        self.tableView.setObjectName("tableView")
        self.tabWidget_10.addTab(self.tab_33, "")
        self.tab_34 = QtWidgets.QWidget()
        self.tab_34.setObjectName("tab_34")
        self.tableView_31 = QtWidgets.QTableView(self.tab_34)
        self.tableView_31.setGeometry(QtCore.QRect(3, 4, 1061, 581))
        self.tableView_31.setObjectName("tableView_31")
        self.tabWidget_10.addTab(self.tab_34, "")
        self.tab_35 = QtWidgets.QWidget()
        self.tab_35.setObjectName("tab_35")
        self.tableView_32 = QtWidgets.QTableView(self.tab_35)
        self.tableView_32.setGeometry(QtCore.QRect(3, 4, 1061, 581))
        self.tableView_32.setObjectName("tableView_32")
        self.tabWidget_10.addTab(self.tab_35, "")
        self.tabWidget_4.addTab(self.tab_18, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.tableView_7 = QtWidgets.QTableView(self.tab_19)
        self.tableView_7.setGeometry(QtCore.QRect(3, 4, 1067, 614))
        self.tableView_7.setObjectName("tableView_7")
        self.tabWidget_4.addTab(self.tab_19, "")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.tableView_13 = QtWidgets.QTableView(self.tab_20)
        self.tableView_13.setGeometry(QtCore.QRect(3, 4, 1068, 614))
        self.tableView_13.setObjectName("tableView_13")
        self.tabWidget_4.addTab(self.tab_20, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.tableView_14 = QtWidgets.QTableView(self.tab_21)
        self.tableView_14.setGeometry(QtCore.QRect(3, 4, 1068, 614))
        self.tableView_14.setObjectName("tableView_14")
        self.tabWidget_4.addTab(self.tab_21, "")
        self.tab_22 = QtWidgets.QWidget()
        self.tab_22.setObjectName("tab_22")
        self.tableView_15 = QtWidgets.QTableView(self.tab_22)
        self.tableView_15.setGeometry(QtCore.QRect(3, 4, 1068, 614))
        self.tableView_15.setObjectName("tableView_15")
        self.tabWidget_4.addTab(self.tab_22, "")
        self.tab_23 = QtWidgets.QWidget()
        self.tab_23.setObjectName("tab_23")
        self.tableView_16 = QtWidgets.QTableView(self.tab_23)
        self.tableView_16.setGeometry(QtCore.QRect(3, 4, 1068, 614))
        self.tableView_16.setObjectName("tableView_16")
        self.tabWidget_4.addTab(self.tab_23, "")
        self.tab_24 = QtWidgets.QWidget()
        self.tab_24.setObjectName("tab_24")
        self.tableView_17 = QtWidgets.QTableView(self.tab_24)
        self.tableView_17.setGeometry(QtCore.QRect(3, 4, 1068, 614))
        self.tableView_17.setObjectName("tableView_17")
        self.tabWidget_4.addTab(self.tab_24, "")
        self.tab_25 = QtWidgets.QWidget()
        self.tab_25.setObjectName("tab_25")
        self.tableView_18 = QtWidgets.QTableView(self.tab_25)
        self.tableView_18.setGeometry(QtCore.QRect(3, 4, 1068, 614))
        self.tableView_18.setObjectName("tableView_18")
        self.tabWidget_4.addTab(self.tab_25, "")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_36.setGeometry(QtCore.QRect(910, 5, 166, 26))
        self.lineEdit_36.setObjectName("lineEdit_36")

        self.retranslateUi()
        self.tabWidget_4.setCurrentIndex(7)
        self.tabWidget_10.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(self)


        self.country = 'united states'
        self.group = 'metals'

        self.display_markets()

    def display_crypto(self):
        self.coins = investpy.get_cryptos_overview()
        #self.coins_info = investpy.get_crypto_information()
        self.tableView.setModel(PandasModel(self.coins))
        #self.tableView_31.setModel(PandasModel(self.coins))

    def display_stocks(self):
        self.stocks = investpy.stocks.get_stocks_overview(self.country)
        self.tableView_7.setModel(PandasModel(self.stocks))

    def display_indexes(self):
        self.indexes = investpy.get_indices_overview(self.country)
        self.tableView_13.setModel(PandasModel(self.indexes))

    def display_bonds(self):
        self.bonds = investpy.get_bonds_overview(self.country)
        self.tableView_14.setModel(PandasModel(self.bonds))

    def display_certificates(self):
        self.certificates = investpy.get_certificates_overview(self.country)
        self.tableView_15.setModel(PandasModel(self.certificates))

    def display_commodities(self):
        self.commodities = investpy.get_commodities_overview(self.group)
        self.tableView_16.setModel(PandasModel(self.commodities))

    def display_etfs(self):
        self.etfs = investpy.get_etfs_overview(self.country)
        self.tableView_17.setModel(PandasModel(self.etfs))

    def display_funds(self):
        self.funds = investpy.get_funds_overview(self.country)
        self.tableView_18.setModel(PandasModel(self.funds))


    def display_markets(self):
        for func in [self.display_crypto, self.display_stocks, self.display_bonds, self.display_etfs,
                     self.display_funds, self.display_commodities, self.display_certificates, self.display_indexes]:
            try:
                func()
            except:
                pass


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_8.setTitle(_translate("Form", " COMMODITIES   "))
        self.groupBox_4.setTitle(_translate("Form", " CRYPTO     "))
        self.groupBox_6.setTitle(_translate("Form", " FOREX    "))
        self.groupBox_5.setTitle(_translate("Form", " INDEXES      "))
        self.groupBox_7.setTitle(_translate("Form", " BONDS  "))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_16), _translate("Form", "ALL MARKETS"))
        self.tabWidget_10.setTabText(self.tabWidget_10.indexOf(self.tab_33), _translate("Form", "PRICES"))
        self.tabWidget_10.setTabText(self.tabWidget_10.indexOf(self.tab_34), _translate("Form", "INFO"))
        self.tabWidget_10.setTabText(self.tabWidget_10.indexOf(self.tab_35), _translate("Form", "GLOBAL METRICS"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_18), _translate("Form", "CRYPTO"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_19), _translate("Form", "STOCKS"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_20), _translate("Form", "INDEXES"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_21), _translate("Form", "BONDS"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_22), _translate("Form", "CERTIFICATES"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_23), _translate("Form", "COMMODITIES"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_24), _translate("Form", "ETFs"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_25), _translate("Form", "FUNDS"))


