

from PyQt5 import QtCore, QtGui, QtWidgets


class PortfolioWidget(QtWidgets.QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.setObjectName("PORTFOLIO")
        self.resize(1082, 659)
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1081, 661))
        self.widget.setObjectName("widget")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_35.setGeometry(QtCore.QRect(910, 5, 166, 23))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.pushButton_27 = QtWidgets.QPushButton(self.widget)
        self.pushButton_27.setGeometry(QtCore.QRect(5, 5, 23, 23))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet("font: 75  16pt \"Ubuntu Bold\";")
        self.pushButton_27.setObjectName("pushButton_27")
        self.line_11 = QtWidgets.QFrame(self.widget)
        self.line_11.setGeometry(QtCore.QRect(0, 27, 1076, 16))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.comboBox_4 = QtWidgets.QComboBox(self.widget)
        self.comboBox_4.setGeometry(QtCore.QRect(145, 5, 111, 23))
        self.comboBox_4.setObjectName("comboBox_4")
        self.pushButton_58 = QtWidgets.QPushButton(self.widget)
        self.pushButton_58.setGeometry(QtCore.QRect(110, 5, 23, 23))
        self.pushButton_58.setObjectName("pushButton_58")
        self.pushButton_28 = QtWidgets.QPushButton(self.widget)
        self.pushButton_28.setGeometry(QtCore.QRect(40, 5, 23, 23))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_26 = QtWidgets.QPushButton(self.widget)
        self.pushButton_26.setGeometry(QtCore.QRect(75, 5, 23, 23))
        self.pushButton_26.setObjectName("pushButton_26")
        self.tabWidget_11 = QtWidgets.QTabWidget(self.widget)
        self.tabWidget_11.setGeometry(QtCore.QRect(0, 35, 1076, 619))
        self.tabWidget_11.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.tabWidget_11.setObjectName("tabWidget_11")
        self.tab_28 = QtWidgets.QWidget()
        self.tab_28.setObjectName("tab_28")
        self.tableView_33 = QtWidgets.QTableView(self.tab_28)
        self.tableView_33.setGeometry(QtCore.QRect(3, 4, 1066, 580))
        self.tableView_33.setObjectName("tableView_33")
        self.tabWidget_11.addTab(self.tab_28, "")
        self.pushButton_29 = QtWidgets.QPushButton(self.widget)
        self.pushButton_29.setGeometry(QtCore.QRect(265, 5, 23, 23))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Bold")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setStyleSheet("font: 75  13pt \"Ubuntu Bold\";")
        self.pushButton_29.setObjectName("pushButton_29")

        self.retranslateUi()
        self.tabWidget_11.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self,):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_27.setText(_translate("Form", "+"))
        self.pushButton_58.setText(_translate("Form", "del"))
        self.pushButton_28.setText(_translate("Form", "op"))
        self.pushButton_26.setText(_translate("Form", "sv"))
        self.tabWidget_11.setTabText(self.tabWidget_11.indexOf(self.tab_28), _translate("Form", "PORTFOLIO 1"))
        self.pushButton_29.setText(_translate("Form", "X"))



