
from PyQt5 import QtCore, QtGui, QtWidgets


class TrendsWidget(QtWidgets.QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.setObjectName("TRENDS")
        self.resize(1083, 660)
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1081, 656))
        self.widget.setObjectName("widget")
        self.groupBox_29 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_29.setGeometry(QtCore.QRect(0, 330, 1076, 320))
        self.groupBox_29.setMinimumSize(QtCore.QSize(0, 180))
        self.groupBox_29.setMaximumSize(QtCore.QSize(16777215, 320))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_29.setFont(font)
        self.groupBox_29.setObjectName("groupBox_29")
        self.groupBox_30 = QtWidgets.QGroupBox(self.groupBox_29)
        self.groupBox_30.setGeometry(QtCore.QRect(645, 30, 216, 290))
        self.groupBox_30.setMinimumSize(QtCore.QSize(216, 160))
        self.groupBox_30.setMaximumSize(QtCore.QSize(216, 300))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_30.setFont(font)
        self.groupBox_30.setObjectName("groupBox_30")
        self.tableView_26 = QtWidgets.QTableView(self.groupBox_30)
        self.tableView_26.setGeometry(QtCore.QRect(5, 30, 206, 256))
        self.tableView_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_26.setObjectName("tableView_26")
        self.tableView_26.horizontalHeader().setVisible(False)
        self.groupBox_31 = QtWidgets.QGroupBox(self.groupBox_29)
        self.groupBox_31.setGeometry(QtCore.QRect(0, 30, 216, 290))
        self.groupBox_31.setMinimumSize(QtCore.QSize(216, 160))
        self.groupBox_31.setMaximumSize(QtCore.QSize(216, 300))
        self.groupBox_31.setSizeIncrement(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_31.setFont(font)
        self.groupBox_31.setAutoFillBackground(False)
        self.groupBox_31.setObjectName("groupBox_31")
        self.tableView_27 = QtWidgets.QTableView(self.groupBox_31)
        self.tableView_27.setGeometry(QtCore.QRect(5, 30, 206, 256))
        self.tableView_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_27.setObjectName("tableView_27")
        self.tableView_27.horizontalHeader().setVisible(False)
        self.groupBox_32 = QtWidgets.QGroupBox(self.groupBox_29)
        self.groupBox_32.setGeometry(QtCore.QRect(430, 30, 216, 290))
        self.groupBox_32.setMinimumSize(QtCore.QSize(216, 160))
        self.groupBox_32.setMaximumSize(QtCore.QSize(216, 300))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_32.setFont(font)
        self.groupBox_32.setObjectName("groupBox_32")
        self.tableView_28 = QtWidgets.QTableView(self.groupBox_32)
        self.tableView_28.setGeometry(QtCore.QRect(5, 30, 206, 256))
        self.tableView_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_28.setObjectName("tableView_28")
        self.tableView_28.horizontalHeader().setVisible(False)
        self.groupBox_33 = QtWidgets.QGroupBox(self.groupBox_29)
        self.groupBox_33.setEnabled(True)
        self.groupBox_33.setGeometry(QtCore.QRect(860, 30, 216, 290))
        self.groupBox_33.setMinimumSize(QtCore.QSize(216, 160))
        self.groupBox_33.setMaximumSize(QtCore.QSize(216, 300))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_33.setFont(font)
        self.groupBox_33.setStyleSheet("font: 63 13pt \"FixedsysTTF\";")
        self.groupBox_33.setObjectName("groupBox_33")
        self.tableView_29 = QtWidgets.QTableView(self.groupBox_33)
        self.tableView_29.setGeometry(QtCore.QRect(5, 30, 206, 256))
        self.tableView_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_29.setObjectName("tableView_29")
        self.tableView_29.horizontalHeader().setVisible(False)
        self.groupBox_34 = QtWidgets.QGroupBox(self.groupBox_29)
        self.groupBox_34.setGeometry(QtCore.QRect(215, 30, 216, 290))
        self.groupBox_34.setMinimumSize(QtCore.QSize(216, 160))
        self.groupBox_34.setMaximumSize(QtCore.QSize(216, 300))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_34.setFont(font)
        self.groupBox_34.setObjectName("groupBox_34")
        self.tableView_30 = QtWidgets.QTableView(self.groupBox_34)
        self.tableView_30.setGeometry(QtCore.QRect(5, 30, 206, 256))
        self.tableView_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_30.setObjectName("tableView_30")
        self.tableView_30.horizontalHeader().setVisible(False)
        self.groupBox_23 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_23.setGeometry(QtCore.QRect(0, 5, 1076, 320))
        self.groupBox_23.setMinimumSize(QtCore.QSize(0, 180))
        self.groupBox_23.setMaximumSize(QtCore.QSize(16777215, 320))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_23.setFont(font)
        self.groupBox_23.setObjectName("groupBox_23")
        self.groupBox_24 = QtWidgets.QGroupBox(self.groupBox_23)
        self.groupBox_24.setGeometry(QtCore.QRect(645, 30, 216, 290))
        self.groupBox_24.setMinimumSize(QtCore.QSize(216, 160))
        self.groupBox_24.setMaximumSize(QtCore.QSize(216, 300))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_24.setFont(font)
        self.groupBox_24.setObjectName("groupBox_24")
        self.tableView_21 = QtWidgets.QTableView(self.groupBox_24)
        self.tableView_21.setGeometry(QtCore.QRect(5, 30, 206, 256))
        self.tableView_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_21.setObjectName("tableView_21")
        self.tableView_21.horizontalHeader().setVisible(False)
        self.groupBox_25 = QtWidgets.QGroupBox(self.groupBox_23)
        self.groupBox_25.setGeometry(QtCore.QRect(0, 30, 216, 290))
        self.groupBox_25.setMinimumSize(QtCore.QSize(216, 160))
        self.groupBox_25.setMaximumSize(QtCore.QSize(216, 300))
        self.groupBox_25.setSizeIncrement(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_25.setFont(font)
        self.groupBox_25.setAutoFillBackground(False)
        self.groupBox_25.setObjectName("groupBox_25")
        self.tableView_22 = QtWidgets.QTableView(self.groupBox_25)
        self.tableView_22.setGeometry(QtCore.QRect(5, 30, 206, 256))
        self.tableView_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_22.setObjectName("tableView_22")
        self.tableView_22.horizontalHeader().setVisible(False)
        self.groupBox_26 = QtWidgets.QGroupBox(self.groupBox_23)
        self.groupBox_26.setGeometry(QtCore.QRect(430, 30, 216, 290))
        self.groupBox_26.setMinimumSize(QtCore.QSize(216, 160))
        self.groupBox_26.setMaximumSize(QtCore.QSize(216, 300))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_26.setFont(font)
        self.groupBox_26.setObjectName("groupBox_26")
        self.tableView_23 = QtWidgets.QTableView(self.groupBox_26)
        self.tableView_23.setGeometry(QtCore.QRect(5, 30, 206, 256))
        self.tableView_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_23.setObjectName("tableView_23")
        self.tableView_23.horizontalHeader().setVisible(False)
        self.groupBox_27 = QtWidgets.QGroupBox(self.groupBox_23)
        self.groupBox_27.setEnabled(True)
        self.groupBox_27.setGeometry(QtCore.QRect(860, 30, 216, 290))
        self.groupBox_27.setMinimumSize(QtCore.QSize(216, 160))
        self.groupBox_27.setMaximumSize(QtCore.QSize(216, 300))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_27.setFont(font)
        self.groupBox_27.setStyleSheet("font: 63 13pt \"FixedsysTTF\";")
        self.groupBox_27.setObjectName("groupBox_27")
        self.tableView_24 = QtWidgets.QTableView(self.groupBox_27)
        self.tableView_24.setGeometry(QtCore.QRect(5, 30, 206, 256))
        self.tableView_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_24.setObjectName("tableView_24")
        self.tableView_24.horizontalHeader().setVisible(False)
        self.groupBox_28 = QtWidgets.QGroupBox(self.groupBox_23)
        self.groupBox_28.setGeometry(QtCore.QRect(215, 30, 216, 290))
        self.groupBox_28.setMinimumSize(QtCore.QSize(216, 160))
        self.groupBox_28.setMaximumSize(QtCore.QSize(216, 300))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_28.setFont(font)
        self.groupBox_28.setObjectName("groupBox_28")
        self.tableView_25 = QtWidgets.QTableView(self.groupBox_28)
        self.tableView_25.setGeometry(QtCore.QRect(5, 30, 206, 256))
        self.tableView_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableView_25.setObjectName("tableView_25")
        self.tableView_25.horizontalHeader().setVisible(False)
        self.comboBox_19 = QtWidgets.QComboBox(self.groupBox_23)
        self.comboBox_19.setGeometry(QtCore.QRect(990, 0, 81, 21))
        self.comboBox_19.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.comboBox_19.setObjectName("comboBox_19")
        self.label_49 = QtWidgets.QLabel(self.groupBox_23)
        self.label_49.setGeometry(QtCore.QRect(910, 0, 76, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.label_49.setObjectName("label_49")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_29.setTitle(_translate("Form", " TOP LOSERS "))
        self.groupBox_30.setTitle(_translate("Form", " BONDS  "))
        self.groupBox_31.setTitle(_translate("Form", " CRYPTO     "))
        self.groupBox_32.setTitle(_translate("Form", " FOREX    "))
        self.groupBox_33.setTitle(_translate("Form", " COMMODITIES   "))
        self.groupBox_34.setTitle(_translate("Form", " INDEXES      "))
        self.groupBox_23.setTitle(_translate("Form", " TOP GAINERS "))
        self.groupBox_24.setTitle(_translate("Form", " BONDS  "))
        self.groupBox_25.setTitle(_translate("Form", " CRYPTO     "))
        self.groupBox_26.setTitle(_translate("Form", " FOREX    "))
        self.groupBox_27.setTitle(_translate("Form", " COMMODITIES   "))
        self.groupBox_28.setTitle(_translate("Form", " INDEXES      "))
        self.label_49.setText(_translate("Form", "TIMEFRAME"))


