

from PyQt5 import QtCore, QtGui, QtWidgets


class WatchlistWidget(QtWidgets.QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.setObjectName("WATCHLIST")
        self.resize(1084, 664)
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1081, 656))
        self.widget.setObjectName("widget")
        self.pushButton_56 = QtWidgets.QPushButton(self.widget)
        self.pushButton_56.setGeometry(QtCore.QRect(110, 5, 23, 23))
        self.pushButton_56.setObjectName("pushButton_56")
        self.line_12 = QtWidgets.QFrame(self.widget)
        self.line_12.setGeometry(QtCore.QRect(0, 27, 1076, 16))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.pushButton_34 = QtWidgets.QPushButton(self.widget)
        self.pushButton_34.setGeometry(QtCore.QRect(5, 5, 23, 23))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Bold")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setStyleSheet("font: 75  16pt \"Ubuntu Bold\";")
        self.pushButton_34.setObjectName("pushButton_34")
        self.comboBox_20 = QtWidgets.QComboBox(self.widget)
        self.comboBox_20.setGeometry(QtCore.QRect(145, 5, 111, 23))
        self.comboBox_20.setObjectName("comboBox_20")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_42.setGeometry(QtCore.QRect(910, 5, 166, 23))
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.pushButton_55 = QtWidgets.QPushButton(self.widget)
        self.pushButton_55.setGeometry(QtCore.QRect(40, 5, 23, 23))
        self.pushButton_55.setObjectName("pushButton_55")
        self.pushButton_30 = QtWidgets.QPushButton(self.widget)
        self.pushButton_30.setGeometry(QtCore.QRect(75, 5, 23, 23))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_46 = QtWidgets.QPushButton(self.widget)
        self.pushButton_46.setGeometry(QtCore.QRect(265, 5, 23, 23))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Bold")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.pushButton_46.setFont(font)
        self.pushButton_46.setStyleSheet("font: 75  13pt \"Ubuntu Bold\";")
        self.pushButton_46.setObjectName("pushButton_46")
        self.tabWidget_8 = QtWidgets.QTabWidget(self.widget)
        self.tabWidget_8.setGeometry(QtCore.QRect(0, 35, 1076, 618))
        self.tabWidget_8.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.tabWidget_8.setObjectName("tabWidget_8")
        self.tab_27 = QtWidgets.QWidget()
        self.tab_27.setObjectName("tab_27")
        self.tableView_11 = QtWidgets.QTableView(self.tab_27)
        self.tableView_11.setGeometry(QtCore.QRect(3, 4, 1066, 580))
        self.tableView_11.setObjectName("tableView_11")
        self.tabWidget_8.addTab(self.tab_27, "")

        self.retranslateUi()
        self.tabWidget_8.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_56.setText(_translate("Form", "del"))
        self.pushButton_34.setText(_translate("Form", "+"))
        self.pushButton_55.setText(_translate("Form", "op"))
        self.pushButton_30.setText(_translate("Form", "sv"))
        self.pushButton_46.setText(_translate("Form", "X"))
        self.tabWidget_8.setTabText(self.tabWidget_8.indexOf(self.tab_27), _translate("Form", "WATCHLIST 1"))


