import yaml
from PyQt5 import QtCore, QtWidgets
from ui.markets_widget import MarketsWidget
from ui.oldwidgets.news_widget import NewsWidget
from ui.settings_window import SettingsWindow
from ui.oldwidgets.trade_widget import TradeWidget
from ui.oldwidgets.watchlist_widget import WatchlistWidget
from ui.oldwidgets.algorithms_widget import AlgorithmsWidget
from ui.oldwidgets.charts_widget import ChartsWidget
from ui.editor_widget import EditorWidget
from ui.database_widget import DatabaseWidget
from ui.oldwidgets.portfolio_widget import PortfolioWidget
from ui.oldwidgets.calendar_widget import CalendarWidget
from ui.fx_widget import FXWidget
from ui.fundamentals5 import FundamentalsWidget



class FrontZaur(QtWidgets.QMainWindow):
    def __init__(self, username, backend):
        super().__init__()
        self.datazaur = backend
        self.username = username

        self.config = None
        self.widgets = {'markets': MarketsWidget, 'news': NewsWidget, 'trade': TradeWidget,
                        'watchlist': WatchlistWidget, 'algorithms': AlgorithmsWidget, 'charts': ChartsWidget,
                        'editor': EditorWidget, 'database': DatabaseWidget, 'portfolio': PortfolioWidget,
                        'fundamentals': FundamentalsWidget, 'calendar': CalendarWidget, 'currencies': FXWidget,
                        }

        self.setObjectName("Datazaur")
        #self.setStyleSheet(GLOBAL_STYLE)
        self.resize(1225, 767)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1211, 721))
        self.widget.setObjectName("widget")
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(5, 0, 1206, 721))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget1)
        self.groupBox.setMinimumSize(QtCore.QSize(220, 600))
        self.groupBox.setMaximumSize(QtCore.QSize(250, 700))
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(8, 27, 131, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(148, 27, 66, 25))
        self.pushButton.setObjectName("pushButton")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setGeometry(QtCore.QRect(5, 60, 211, 131))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 209, 129))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(5, 5, 196, 116))
        self.listWidget.setObjectName("listWidget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 200, 211, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 30, 89, 26))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setGeometry(QtCore.QRect(115, 30, 89, 26))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(115, 65, 89, 26))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 135, 194, 26))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 65, 89, 26))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setGeometry(QtCore.QRect(115, 100, 89, 26))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 100, 89, 26))
        self.pushButton_8.setObjectName("pushButton_8")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(5, 385, 211, 166))
        self.groupBox_5.setObjectName("groupBox_5")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton.setGeometry(QtCore.QRect(5, 30, 51, 25))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_2.setGeometry(QtCore.QRect(5, 65, 61, 25))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_3.setGeometry(QtCore.QRect(100, 65, 101, 25))
        self.radioButton_3.setObjectName("radioButton_3")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_5)
        self.dateTimeEdit.setGeometry(QtCore.QRect(50, 135, 156, 25))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.comboBox_13 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_13.setGeometry(QtCore.QRect(100, 30, 106, 25))
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.groupBox_5)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(50, 100, 156, 25))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 36, 25))
        self.label_5.setObjectName("label_5")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(10, 135, 31, 25))
        self.label_15.setObjectName("label_15")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 565, 201, 126))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout.addWidget(self.groupBox)
        self.tabWidget = QtWidgets.QTabWidget(self.widget1)
        self.tabWidget.setMinimumSize(QtCore.QSize(700, 600))
        self.tabWidget.setMaximumSize(QtCore.QSize(978, 719))
        self.tabWidget.setObjectName("tabWidget")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1225, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuThemes = QtWidgets.QMenu(self.menuSettings)
        self.menuThemes.setObjectName("menuThemes")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuModels = QtWidgets.QMenu(self.menuTools)
        self.menuModels.setObjectName("menuModels")
        self.menuCorrelograms = QtWidgets.QMenu(self.menuTools)
        self.menuCorrelograms.setObjectName("menuCorrelograms")
        self.menuCointegration = QtWidgets.QMenu(self.menuTools)
        self.menuCointegration.setObjectName("menuCointegration")
        self.menuCrypto = QtWidgets.QMenu(self.menubar)
        self.menuCrypto.setObjectName("menuCrypto")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionMarkets = QtWidgets.QAction(self)
        self.actionMarkets.setCheckable(True)
        self.actionMarkets.setChecked(True)
        self.actionMarkets.setObjectName("actionMarkets")
        self.actionTrade = QtWidgets.QAction(self)
        self.actionTrade.setCheckable(True)
        self.actionTrade.setChecked(True)
        self.actionTrade.setObjectName("actionTrade")
        self.actionCharts = QtWidgets.QAction(self)
        self.actionCharts.setCheckable(True)
        self.actionCharts.setChecked(True)
        self.actionCharts.setObjectName("actionCharts")
        self.actionWatchlist = QtWidgets.QAction(self)
        self.actionWatchlist.setCheckable(True)
        self.actionWatchlist.setChecked(True)
        self.actionWatchlist.setObjectName("actionWatchlist")
        self.actionAlgorithm_Wizard = QtWidgets.QAction(self)
        self.actionAlgorithm_Wizard.setCheckable(True)
        self.actionAlgorithm_Wizard.setChecked(True)
        self.actionAlgorithm_Wizard.setObjectName("actionAlgorithm_Wizard")
        self.actionPortfolio = QtWidgets.QAction(self)
        self.actionPortfolio.setObjectName("actionPortfolio")
        self.actionScript_Editor = QtWidgets.QAction(self)
        self.actionScript_Editor.setCheckable(True)
        self.actionScript_Editor.setChecked(True)
        self.actionScript_Editor.setObjectName("actionScript_Editor")
        self.actionDatabase = QtWidgets.QAction(self)
        self.actionDatabase.setCheckable(True)
        self.actionDatabase.setObjectName("actionDatabase")
        self.actionNews_Feed = QtWidgets.QAction(self)
        self.actionNews_Feed.setCheckable(True)
        self.actionNews_Feed.setChecked(True)
        self.actionNews_Feed.setObjectName("actionNews_Feed")
        self.actionSettings = QtWidgets.QAction(self)
        self.actionSettings.setObjectName("actionSettings")
        self.actionNavy = QtWidgets.QAction(self)
        self.actionNavy.setObjectName("actionNavy")
        self.actionMatrix = QtWidgets.QAction(self)
        self.actionMatrix.setObjectName("actionMatrix")
        self.actionAbout = QtWidgets.QAction(self)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDonate = QtWidgets.QAction(self)
        self.actionDonate.setObjectName("actionDonate")
        self.actionContribute = QtWidgets.QAction(self)
        self.actionContribute.setObjectName("actionContribute")
        self.actionHelp = QtWidgets.QAction(self)
        self.actionHelp.setObjectName("actionHelp")
        self.actionADF = QtWidgets.QAction(self)
        self.actionADF.setObjectName("actionADF")
        self.actionKPSS_test = QtWidgets.QAction(self)
        self.actionKPSS_test.setObjectName("actionKPSS_test")
        self.actionEngle_Granger_test = QtWidgets.QAction(self)
        self.actionEngle_Granger_test.setObjectName("actionEngle_Granger_test")
        self.actionJohansen = QtWidgets.QAction(self)
        self.actionJohansen.setObjectName("actionJohansen")
        self.actionBacktest = QtWidgets.QAction(self)
        self.actionBacktest.setObjectName("actionBacktest")
        self.actionCustom = QtWidgets.QAction(self)
        self.actionCustom.setObjectName("actionCustom")
        self.actionFX_Rates = QtWidgets.QAction(self)
        self.actionFX_Rates.setObjectName("actionFX_Rates")
        self.actionOLS_Model = QtWidgets.QAction(self)
        self.actionOLS_Model.setObjectName("actionOLS_Model")
        self.actionReport_a_bug = QtWidgets.QAction(self)
        self.actionReport_a_bug.setObjectName("actionReport_a_bug")
        self.actionEthereum_Explorer = QtWidgets.QAction(self)
        self.actionEthereum_Explorer.setObjectName("actionEthereum_Explorer")
        self.actionBitcoin_Explorer = QtWidgets.QAction(self)
        self.actionBitcoin_Explorer.setObjectName("actionBitcoin_Explorer")
        self.actionCrypto_wallet = QtWidgets.QAction(self)
        self.actionCrypto_wallet.setObjectName("actionCrypto_wallet")
        self.actionMacro_data = QtWidgets.QAction(self)
        self.actionMacro_data.setObjectName("actionMacro_data")
        self.actionOptions_Calculator = QtWidgets.QAction(self)
        self.actionOptions_Calculator.setObjectName("actionOptions_Calculator")
        self.actionStationarity = QtWidgets.QAction(self)
        self.actionStationarity.setObjectName("actionStationarity")
        self.actionDescriptive_statistics = QtWidgets.QAction(self)
        self.actionDescriptive_statistics.setObjectName("actionDescriptive_statistics")
        self.actionOLS = QtWidgets.QAction(self)
        self.actionOLS.setObjectName("actionOLS")
        self.actionARMA = QtWidgets.QAction(self)
        self.actionARMA.setObjectName("actionARMA")
        self.actionACF = QtWidgets.QAction(self)
        self.actionACF.setObjectName("actionACF")
        self.actionPACF = QtWidgets.QAction(self)
        self.actionPACF.setObjectName("actionPACF")
        self.actionEngle_Granger = QtWidgets.QAction(self)
        self.actionEngle_Granger.setObjectName("actionEngle_Granger")
        self.actionJohansen_2 = QtWidgets.QAction(self)
        self.actionJohansen_2.setObjectName("actionJohansen_2")
        self.actionBlockchain_Explorer = QtWidgets.QAction(self)
        self.actionBlockchain_Explorer.setObjectName("actionBlockchain_Explorer")
        self.actionWallet = QtWidgets.QAction(self)
        self.actionWallet.setObjectName("actionWallet")
        self.menuView.addAction(self.actionMarkets)
        self.menuView.addAction(self.actionTrade)
        self.menuView.addAction(self.actionCharts)
        self.menuView.addAction(self.actionWatchlist)
        self.menuView.addAction(self.actionFX_Rates)
        self.menuView.addAction(self.actionOptions_Calculator)
        self.menuView.addAction(self.actionPortfolio)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionNews_Feed)
        self.menuView.addAction(self.actionMacro_data)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionAlgorithm_Wizard)
        self.menuView.addAction(self.actionScript_Editor)
        self.menuView.addAction(self.actionDatabase)
        self.menuView.addSeparator()
        self.menuView.addSeparator()
        self.menuThemes.addAction(self.actionNavy)
        self.menuThemes.addAction(self.actionMatrix)
        self.menuThemes.addSeparator()
        self.menuThemes.addAction(self.actionCustom)
        self.menuSettings.addAction(self.actionSettings)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.menuThemes.menuAction())
        self.menuSettings.addSeparator()
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionReport_a_bug)
        self.menuHelp.addAction(self.actionContribute)
        self.menuHelp.addAction(self.actionDonate)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuModels.addAction(self.actionOLS)
        self.menuModels.addAction(self.actionARMA)
        self.menuCorrelograms.addAction(self.actionACF)
        self.menuCorrelograms.addAction(self.actionPACF)
        self.menuCointegration.addAction(self.actionEngle_Granger)
        self.menuCointegration.addAction(self.actionJohansen_2)
        self.menuTools.addAction(self.actionDescriptive_statistics)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.menuCorrelograms.menuAction())
        self.menuTools.addAction(self.actionStationarity)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.menuModels.menuAction())
        self.menuTools.addAction(self.menuCointegration.menuAction())
        self.menuTools.addSeparator()
        self.menuCrypto.addAction(self.actionBlockchain_Explorer)
        self.menuCrypto.addAction(self.actionWallet)
        self.menuCrypto.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuCrypto.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

        self.tabWidget.setMovable(True)

        self.load_config()
        self.load_default_widgets()

        self.actionSettings.triggered.connect(self.open_settings)

        self.actionMarkets.triggered.connect(lambda: self.toggle_widget(MarketsWidget, self.actionMarkets.isChecked(), self.actionMarkets.text()))
        self.actionTrade.triggered.connect(lambda: self.toggle_widget(TradeWidget, self.actionTrade.isChecked(), self.actionTrade.text()))
        self.actionCharts.triggered.connect(lambda: self.toggle_widget(ChartsWidget, self.actionCharts.isChecked(), self.actionCharts.text()))
        self.actionWatchlist.triggered.connect(
            lambda: self.toggle_widget(WatchlistWidget, self.actionWatchlist.isChecked(), self.actionWatchlist.text()))
        # self.actionFX_Rates.triggered.connect(lambda: self.toggle_widget(F))
        # self.actionOptions_Calculator.triggered.connect(lambda: self.toggle_widget(MarketsWidget))
        # self.actionPortfolio_Manager.triggered.connect(lambda: self.toggle_widget(MarketsWidget))
        self.actionNews_Feed.triggered.connect(lambda: self.toggle_widget(NewsWidget, self.actionNews_Feed.isChecked(), self.actionNews_Feed.text()))
        # self.actionMacro_data.triggered.connect(lambda: self.toggle_widget())
        self.actionAlgorithm_Wizard.triggered.connect(
            lambda: self.toggle_widget(AlgorithmsWidget, self.actionAlgorithm_Wizard.isChecked(), self.actionAlgorithm_Wizard.text()))
        self.actionScript_Editor.triggered.connect(
            lambda: self.toggle_widget(EditorWidget, self.actionScript_Editor.isChecked(), self.actionScript_Editor.text()))
        self.actionDatabase.triggered.connect(
            lambda: self.toggle_widget(DatabaseWidget, self.actionDatabase.isChecked(), self.actionDatabase.text()))
        self.actionDatabase.triggered.connect(
            lambda: self.toggle_widget(DatabaseWidget, self.actionDatabase.isChecked(), self.actionDatabase.text()))

        #self.actionFundamental_Data.triggered.connect(
        #    lambda: self.toggle_widget(FundamentalsWidget, self.actionFundamental_Data.isChecked(), self.actionFundamental_Data.text()))


    def load_config(self):
        with open(SETTINGS_FILE) as config:
            self.config = yaml.safe_load(config)

    def load_default_widgets(self):
        for widget_name in self.config['DEFAULT_WIDGETS']:
            self.add_widget(self.widgets[widget_name])


    def find_widget(self, widget_name):
        for i in range(self.tabWidget.count()):
            if self.tabWidget.tabText(i) == widget_name:
                return i
        return None

    def add_widget(self, widget):
        new_widget = widget(self.tabWidget)
        tab_index = self.find_widget(new_widget.objectName())
        if not tab_index:
            self.tabWidget.addTab(new_widget, new_widget.objectName())
        else:
            self.tabWidget.setCurrentIndex(tab_index)


    def toggle_widget(self, widget, checked, widget_name):
        if checked:
            self.add_widget(widget)
        else:
            tab_index = self.find_widget(widget_name)
            self.tabWidget.removeTab(tab_index)


    def close_widget(self, widget_name):
        tab_index = self.find_widget(widget_name)
        if not tab_index:
            return
        else:
            self.tabWidget.removeTab(tab_index)

    def show_widget(self):
        pass

    def hide_widget(self):
        pass

    def set_timeframe_mode(self):
        pass

    def set_timeframe(self):
        pass

    def search(self):
        pass

    def open_settings(self):
        settings_window = SettingsWindow()
        settings_window.show()
        settings_window.exec()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Datazaur"))
        self.groupBox.setTitle(_translate("MainWindow", "    DATAZAUR"))
        self.pushButton.setText(_translate("MainWindow", "search"))
        self.groupBox_3.setTitle(_translate("MainWindow", "   actions "))
        self.pushButton_2.setText(_translate("MainWindow", "watch"))
        self.pushButton_3.setText(_translate("MainWindow", "chart"))
        self.pushButton_4.setText(_translate("MainWindow", "trade"))
        self.pushButton_5.setText(_translate("MainWindow", "calculate return"))
        self.pushButton_6.setText(_translate("MainWindow", "quote"))
        self.pushButton_7.setText(_translate("MainWindow", "variables"))
        self.pushButton_8.setText(_translate("MainWindow", "alert"))
        self.groupBox_5.setTitle(_translate("MainWindow", "  timeframe"))
        self.radioButton.setText(_translate("MainWindow", "last"))
        self.radioButton_2.setText(_translate("MainWindow", "since"))
        self.radioButton_3.setText(_translate("MainWindow", "range"))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "12h"))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "1d"))
        self.comboBox_13.setItemText(2, _translate("MainWindow", "2d"))
        self.comboBox_13.setItemText(3, _translate("MainWindow", "3d"))
        self.comboBox_13.setItemText(4, _translate("MainWindow", "5d"))
        self.comboBox_13.setItemText(5, _translate("MainWindow", "1w"))
        self.comboBox_13.setItemText(6, _translate("MainWindow", "2w"))
        self.comboBox_13.setItemText(7, _translate("MainWindow", "1M"))
        self.comboBox_13.setItemText(8, _translate("MainWindow", "2M"))
        self.comboBox_13.setItemText(9, _translate("MainWindow", "3M"))
        self.comboBox_13.setItemText(10, _translate("MainWindow", "6M"))
        self.comboBox_13.setItemText(11, _translate("MainWindow", "1Y"))
        self.comboBox_13.setItemText(12, _translate("MainWindow", "2Y"))
        self.comboBox_13.setItemText(13, _translate("MainWindow", "3Y"))
        self.comboBox_13.setItemText(14, _translate("MainWindow", "5Y"))
        self.comboBox_13.setItemText(15, _translate("MainWindow", "10Y"))
        self.comboBox_13.setItemText(16, _translate("MainWindow", "all data"))
        self.label_5.setText(_translate("MainWindow", "start"))
        self.label_15.setText(_translate("MainWindow", "end"))
        self.groupBox_2.setTitle(_translate("MainWindow", "  black box"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "Widgets"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuThemes.setTitle(_translate("MainWindow", "Themes"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTools.setTitle(_translate("MainWindow", "Statistics"))
        self.menuModels.setTitle(_translate("MainWindow", "Models"))
        self.menuCorrelograms.setTitle(_translate("MainWindow", "Correlograms"))
        self.menuCointegration.setTitle(_translate("MainWindow", "Cointegration"))
        self.menuCrypto.setTitle(_translate("MainWindow", "Crypto"))
        self.actionMarkets.setText(_translate("MainWindow", "Markets"))
        self.actionTrade.setText(_translate("MainWindow", "Trade"))
        self.actionCharts.setText(_translate("MainWindow", "Charts"))
        self.actionWatchlist.setText(_translate("MainWindow", "Watchlist"))
        self.actionAlgorithm_Wizard.setText(_translate("MainWindow", "Algorithm Wizard"))
        self.actionPortfolio.setText(_translate("MainWindow", "Portfolio Manager"))
        self.actionScript_Editor.setText(_translate("MainWindow", "Script Editor"))
        self.actionDatabase.setText(_translate("MainWindow", "Database"))
        self.actionNews_Feed.setText(_translate("MainWindow", "News Feed"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionNavy.setText(_translate("MainWindow", "Navy"))
        self.actionMatrix.setText(_translate("MainWindow", "Matrix"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionDonate.setText(_translate("MainWindow", "Donate"))
        self.actionContribute.setText(_translate("MainWindow", "Contribute"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionADF.setText(_translate("MainWindow", "ADF test"))
        self.actionKPSS_test.setText(_translate("MainWindow", "KPSS test"))
        self.actionEngle_Granger_test.setText(_translate("MainWindow", "Engle-Granger"))
        self.actionJohansen.setText(_translate("MainWindow", "Johansen"))
        self.actionBacktest.setText(_translate("MainWindow", "Backtest"))
        self.actionCustom.setText(_translate("MainWindow", "Custom"))
        self.actionFX_Rates.setText(_translate("MainWindow", "FX Rates"))
        self.actionOLS_Model.setText(_translate("MainWindow", "OLS Model"))
        self.actionReport_a_bug.setText(_translate("MainWindow", "Report a bug"))
        self.actionEthereum_Explorer.setText(_translate("MainWindow", "Blockchain Explorer"))
        self.actionBitcoin_Explorer.setText(_translate("MainWindow", "Bitcoin Explorer"))
        self.actionCrypto_wallet.setText(_translate("MainWindow", "Crypto Wallet"))
        self.actionMacro_data.setText(_translate("MainWindow", "Macro data"))
        self.actionOptions_Calculator.setText(_translate("MainWindow", "Options Calculator"))
        self.actionStationarity.setText(_translate("MainWindow", "Stationarity"))
        self.actionDescriptive_statistics.setText(_translate("MainWindow", "Descriptive statistics"))
        self.actionOLS.setText(_translate("MainWindow", "OLS"))
        self.actionARMA.setText(_translate("MainWindow", "ARMA"))
        self.actionACF.setText(_translate("MainWindow", "ACF"))
        self.actionPACF.setText(_translate("MainWindow", "PACF"))
        self.actionEngle_Granger.setText(_translate("MainWindow", "Engle-Granger"))
        self.actionJohansen_2.setText(_translate("MainWindow", "Johansen"))
        self.actionBlockchain_Explorer.setText(_translate("MainWindow", "Blockchain Explorer"))
        self.actionWallet.setText(_translate("MainWindow", "Wallet"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    ui = FrontZaur()
    ui.show()
    sys.exit(app.exec_())
