
from PyQt5 import QtCore, QtGui, QtWidgets

from widgets.algorithm_widget import AlgorithmWidget
from widgets.calendar_widget import CalendarWidget
from widgets.editor_widget import EditorWidget
from widgets.explorer_widget import ExplorerWidget
from widgets.monitor_widget0 import MonitorWidget
from widgets.news_widget import NewsWidget
from widgets.portfolio_widget import PortfolioWidget
from ui.oldwidgets.trade_widget import TradeWidget
from widgets.trends_widget import TrendsWidget
from widgets.watchlist_widget import WatchlistWidget



class Frontzaur(QtWidgets.QMainWindow):
    def __init__(self, backend):
        super().__init__(backend)
        self.datazaur = backend
        self.setObjectName("Datazaur")
        self.resize(1326, 874)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1316, 821))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setGeometry(QtCore.QRect(230, 0, 1081, 821))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_13)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1081, 686))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("font: 63 13pt \"FixedsysTTF\";\n"
                                    "selection-background-color: rgb(114, 159, 207);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_26 = QtWidgets.QWidget()
        self.tab_26.setObjectName("tab_26")
        self.frame_15 = QtWidgets.QFrame(self.tab_26)
        self.frame_15.setGeometry(QtCore.QRect(0, 0, 1076, 654))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.tabWidget.addTab(self.tab_26, "")
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setGeometry(QtCore.QRect(0, 0, 226, 821))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.line_2 = QtWidgets.QFrame(self.frame_14)
        self.line_2.setGeometry(QtCore.QRect(219, 0, 16, 49))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(self.frame_14)
        self.label.setGeometry(QtCore.QRect(9, 10, 216, 36))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 63 36pt \"FixedsysTTF\";\n"
                                    "")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.frame_14)
        self.groupBox.setGeometry(QtCore.QRect(4, 58, 221, 761))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(5, 30, 210, 30))
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.listWidget_3 = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_3.setGeometry(QtCore.QRect(5, 110, 210, 197))
        self.listWidget_3.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_3.setObjectName("listWidget_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(115, 70, 100, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("font: 32 13pt \"FixedsysTTF\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(5, 70, 100, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("font: 32 13pt \"FixedsysTTF\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_36 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_36.setGeometry(QtCore.QRect(5, 355, 100, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setStyleSheet("font: 32 13pt \"FixedsysTTF\";")
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_37.setGeometry(QtCore.QRect(5, 315, 100, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setStyleSheet("font: 32 13pt \"FixedsysTTF\";")
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_38.setGeometry(QtCore.QRect(115, 315, 100, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setStyleSheet("font: 32 13pt \"FixedsysTTF\";")
        self.pushButton_38.setObjectName("pushButton_38")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_10.setGeometry(QtCore.QRect(0, 410, 221, 166))
        self.groupBox_10.setStyleSheet("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_6.setContentsMargins(-1, -1, 3, 3)
        self.gridLayout_6.setHorizontalSpacing(3)
        self.gridLayout_6.setVerticalSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_42 = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_6.addWidget(self.label_42, 0, 0, 1, 2)
        self.comboBox_13 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_13.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.comboBox_13.setObjectName("comboBox_13")
        self.gridLayout_6.addWidget(self.comboBox_13, 0, 2, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_6.addWidget(self.radioButton_3, 1, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_6.addWidget(self.radioButton_4, 2, 0, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout_6.addWidget(self.radioButton_5, 3, 0, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_9.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.comboBox_9.setObjectName("comboBox_9")
        self.gridLayout_6.addWidget(self.comboBox_9, 1, 2, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Fixedsys Excelsior 3.01")
        font.setPointSize(8)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setStyleSheet("")
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_6.addWidget(self.dateTimeEdit, 2, 2, 1, 1)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(9)
        self.dateTimeEdit_2.setFont(font)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout_6.addWidget(self.dateTimeEdit_2, 3, 2, 1, 1)
        self.comboBox_10 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_10.setGeometry(QtCore.QRect(115, 355, 101, 31))
        self.comboBox_10.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.pushButton_39 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_39.setGeometry(QtCore.QRect(115, 395, 100, 31))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setStyleSheet("font: 32 13pt \"FixedsysTTF\";")
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_35 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_35.setGeometry(QtCore.QRect(159, 55, 61, 21))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setStyleSheet("font: 32 9pt \"FixedsysTTF\";")
        self.pushButton_35.setObjectName("pushButton_35")
        self.line = QtWidgets.QFrame(self.frame_14)
        self.line.setGeometry(QtCore.QRect(1, 40, 225, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1326, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuWidgets = QtWidgets.QMenu(self.menubar)
        self.menuWidgets.setObjectName("menuWidgets")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuStats = QtWidgets.QMenu(self.menubar)
        self.menuStats.setObjectName("menuStats")
        self.menuModels = QtWidgets.QMenu(self.menuStats)
        self.menuModels.setObjectName("menuModels")
        self.menuCorrelograms = QtWidgets.QMenu(self.menuStats)
        self.menuCorrelograms.setObjectName("menuCorrelograms")
        self.menuStationarity = QtWidgets.QMenu(self.menuStats)
        self.menuStationarity.setObjectName("menuStationarity")
        self.menuCointegration = QtWidgets.QMenu(self.menuStats)
        self.menuCointegration.setObjectName("menuCointegration")
        self.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)
        self.actionHelp = QtWidgets.QAction(self)
        self.actionHelp.setObjectName("actionHelp")
        self.actionContribute = QtWidgets.QAction(self)
        self.actionContribute.setObjectName("actionContribute")
        self.actionDonate = QtWidgets.QAction(self)
        self.actionDonate.setObjectName("actionDonate")
        self.actionAbout = QtWidgets.QAction(self)
        self.actionAbout.setObjectName("actionAbout")
        self.actionDatabase = QtWidgets.QAction(self)
        self.actionDatabase.setObjectName("actionDatabase")
        self.actionOptions_Calculator = QtWidgets.QAction(self)
        self.actionOptions_Calculator.setObjectName("actionOptions_Calculator")
        self.actionCrypto_Wallet = QtWidgets.QAction(self)
        self.actionCrypto_Wallet.setObjectName("actionCrypto_Wallet")
        self.actionBlockchain_Explorer = QtWidgets.QAction(self)
        self.actionBlockchain_Explorer.setObjectName("actionBlockchain_Explorer")
        self.actionOLS = QtWidgets.QAction(self)
        self.actionOLS.setObjectName("actionOLS")
        self.actionACF = QtWidgets.QAction(self)
        self.actionACF.setObjectName("actionACF")
        self.actionPACF = QtWidgets.QAction(self)
        self.actionPACF.setObjectName("actionPACF")
        self.actionADF_test = QtWidgets.QAction(self)
        self.actionADF_test.setObjectName("actionADF_test")
        self.actionKPSS_test = QtWidgets.QAction(self)
        self.actionKPSS_test.setObjectName("actionKPSS_test")
        self.actionEngle_Granger = QtWidgets.QAction(self)
        self.actionEngle_Granger.setObjectName("actionEngle_Granger")
        self.actionJohansen = QtWidgets.QAction(self)
        self.actionJohansen.setObjectName("actionJohansen")
        self.actionDescriptive_statistics = QtWidgets.QAction(self)
        self.actionDescriptive_statistics.setObjectName("actionDescriptive_statistics")
        self.actionSave = QtWidgets.QAction(self)
        self.actionSave.setObjectName("actionSave")
        self.actionSettings = QtWidgets.QAction(self)
        self.actionSettings.setObjectName("actionSettings")
        self.actionClose = QtWidgets.QAction(self)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuWidgets.addAction(self.actionDatabase)
        self.menuWidgets.addAction(self.actionOptions_Calculator)
        self.menuWidgets.addAction(self.actionCrypto_Wallet)
        self.menuWidgets.addAction(self.actionBlockchain_Explorer)
        self.menuSettings.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionContribute)
        self.menuHelp.addAction(self.actionDonate)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuModels.addAction(self.actionOLS)
        self.menuCorrelograms.addAction(self.actionACF)
        self.menuCorrelograms.addAction(self.actionPACF)
        self.menuStationarity.addAction(self.actionADF_test)
        self.menuStationarity.addAction(self.actionKPSS_test)
        self.menuCointegration.addAction(self.actionEngle_Granger)
        self.menuCointegration.addAction(self.actionJohansen)
        self.menuStats.addAction(self.actionDescriptive_statistics)
        self.menuStats.addAction(self.menuModels.menuAction())
        self.menuStats.addAction(self.menuCorrelograms.menuAction())
        self.menuStats.addAction(self.menuStationarity.menuAction())
        self.menuStats.addAction(self.menuCointegration.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuWidgets.menuAction())
        self.menubar.addAction(self.menuStats.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi()
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)


        self.add_widgets()


    def add_widgets(self):
        for widget in [AlgorithmWidget, CalendarWidget, EditorWidget, ExplorerWidget, MonitorWidget, NewsWidget,
                       PortfolioWidget, TradeWidget, TrendsWidget, WatchlistWidget]:
            print(type(widget))
            new_widget = widget(None)
            self.tabWidget.addTab(new_widget, new_widget.objectName())



    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "Datazaur"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("self", "TRADE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("self", "MONITOR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("self", "WATCHLIST"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("self", "PORTFOLIO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("self", "EXPLORER"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("self", "ALGORITHMS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("self", "CALENDAR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("self", "NEWS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("self", "EDITOR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_26), _translate("self", "TRENDS"))
        self.label.setText(_translate("self", "DATAZAUR"))
        self.groupBox.setTitle(_translate("self", " SEARCH   "))
        self.pushButton.setText(_translate("self", "SEARCH"))
        self.pushButton_5.setText(_translate("self", "CLEAR"))
        self.pushButton_36.setText(_translate("self", "ADD TO"))
        self.pushButton_37.setText(_translate("self", "QUOTES"))
        self.pushButton_38.setText(_translate("self", "INFO"))
        self.groupBox_10.setTitle(_translate("self", " TIMEFRAME"))
        self.label_42.setText(_translate("self", "  INTERVAL"))
        self.radioButton_3.setText(_translate("self", "LAST"))
        self.radioButton_4.setText(_translate("self", "SINCE"))
        self.radioButton_5.setText(_translate("self", "RANGE"))
        self.comboBox_10.setItemText(0, _translate("self", "WATCHLIST"))
        self.comboBox_10.setItemText(1, _translate("self", "PORTFOLIO"))
        self.comboBox_10.setItemText(2, _translate("self", "VARIABLES"))
        self.pushButton_39.setText(_translate("self", "CHART"))
        self.pushButton_35.setText(_translate("self", "FILTERS"))
        self.menuFile.setTitle(_translate("self", "File"))
        self.menuWidgets.setTitle(_translate("self", "Widgets"))
        self.menuSettings.setTitle(_translate("self", "Settings"))
        self.menuHelp.setTitle(_translate("self", "Help"))
        self.menuStats.setTitle(_translate("self", "Stats"))
        self.menuModels.setTitle(_translate("self", "Models"))
        self.menuCorrelograms.setTitle(_translate("self", "Correlograms"))
        self.menuStationarity.setTitle(_translate("self", "Stationarity"))
        self.menuCointegration.setTitle(_translate("self", "Cointegration"))
        self.actionHelp.setText(_translate("self", "Help"))
        self.actionContribute.setText(_translate("self", "Contribute"))
        self.actionDonate.setText(_translate("self", "Donate"))
        self.actionAbout.setText(_translate("self", "About"))
        self.actionDatabase.setText(_translate("self", "Database"))
        self.actionOptions_Calculator.setText(_translate("self", "Options Calculator"))
        self.actionCrypto_Wallet.setText(_translate("self", "Crypto Wallet"))
        self.actionBlockchain_Explorer.setText(_translate("self", "Blockchain Explorer"))
        self.actionOLS.setText(_translate("self", "OLS"))
        self.actionACF.setText(_translate("self", "ACF"))
        self.actionPACF.setText(_translate("self", "PACF"))
        self.actionADF_test.setText(_translate("self", "ADF-test"))
        self.actionKPSS_test.setText(_translate("self", "KPSS-test"))
        self.actionEngle_Granger.setText(_translate("self", "Engle-Granger"))
        self.actionJohansen.setText(_translate("self", "Johansen"))
        self.actionDescriptive_statistics.setText(_translate("self", "Descriptive statistics"))
        self.actionSave.setText(_translate("self", "Save.."))
        self.actionSettings.setText(_translate("self", "Settings"))
        self.actionClose.setText(_translate("self", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    front = Frontzaur(None)

    front.show()
    sys.exit(app.exec_())



