


from PyQt5 import QtCore, QtGui, QtWidgets


class TradeWidget(QtWidgets.QWidget):
    def __init__(self, parent):
        super().__init__(parent)
        self.setObjectName("TRADE")
        self.resize(1076, 651)
        self.widget = QtWidgets.QWidget(self)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1071, 646))
        self.widget.setObjectName("widget")
        self.groupBox_15 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_15.setGeometry(QtCore.QRect(0, 0, 516, 646))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setStyleSheet("font: 63 12pt \"FixedsysTTF\";")
        self.groupBox_15.setObjectName("groupBox_15")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_6.setGeometry(QtCore.QRect(130, 28, 106, 26))
        self.pushButton_6.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_15)
        self.comboBox.setGeometry(QtCore.QRect(5, 29, 116, 26))
        self.comboBox.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.comboBox.setObjectName("comboBox")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_7.setGeometry(QtCore.QRect(485, 30, 26, 26))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Bold")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("font: 32 13pt \"Ubuntu Bold\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.groupBox_15)
        self.tabWidget_3.setGeometry(QtCore.QRect(5, 60, 506, 581))
        self.tabWidget_3.setStyleSheet("font: 63 12pt \"FixedsysTTF\";")
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_15)
        self.pushButton_8.setGeometry(QtCore.QRect(260, 28, 76, 26))
        self.pushButton_8.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.groupBox_22 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_22.setGeometry(QtCore.QRect(520, 370, 551, 276))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_22.setFont(font)
        self.groupBox_22.setStyleSheet("font: 63 12pt \"FixedsysTTF\";")
        self.groupBox_22.setObjectName("groupBox_22")
        self.tableView_20 = QtWidgets.QTableView(self.groupBox_22)
        self.tableView_20.setGeometry(QtCore.QRect(5, 65, 541, 206))
        self.tableView_20.setObjectName("tableView_20")
        self.label_46 = QtWidgets.QLabel(self.groupBox_22)
        self.label_46.setGeometry(QtCore.QRect(5, 30, 201, 26))
        self.label_46.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.groupBox_22)
        self.label_47.setGeometry(QtCore.QRect(220, 30, 151, 26))
        self.label_47.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.groupBox_22)
        self.label_48.setGeometry(QtCore.QRect(395, 30, 146, 26))
        self.label_48.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.groupBox_13 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_13.setGeometry(QtCore.QRect(520, 0, 246, 191))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setStyleSheet("font: 63 12pt \"FixedsysTTF\";")
        self.groupBox_13.setObjectName("groupBox_13")
        self.pushButton_32 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_32.setGeometry(QtCore.QRect(10, 140, 106, 41))
        self.pushButton_32.setStyleSheet("font: 32 16pt \"FixedsysTTF\";")
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_33.setGeometry(QtCore.QRect(130, 140, 106, 41))
        self.pushButton_33.setStyleSheet("font: 32 16pt \"FixedsysTTF\";")
        self.pushButton_33.setObjectName("pushButton_33")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_39.setGeometry(QtCore.QRect(130, 35, 106, 26))
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_40.setGeometry(QtCore.QRect(130, 70, 106, 26))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_41.setGeometry(QtCore.QRect(130, 105, 106, 26))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.label_39 = QtWidgets.QLabel(self.groupBox_13)
        self.label_39.setGeometry(QtCore.QRect(15, 35, 101, 26))
        self.label_39.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_13)
        self.label_40.setGeometry(QtCore.QRect(15, 70, 101, 26))
        self.label_40.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupBox_13)
        self.label_41.setGeometry(QtCore.QRect(15, 105, 101, 26))
        self.label_41.setStyleSheet("font: 63 11pt \"FixedsysTTF\";")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.groupBox_14 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_14.setGeometry(QtCore.QRect(910, 0, 161, 391))
        self.groupBox_14.setStyleSheet("font: 63 12pt \"FixedsysTTF\";")
        self.groupBox_14.setObjectName("groupBox_14")
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox_14)
        self.listWidget_2.setGeometry(QtCore.QRect(10, 30, 141, 146))
        self.listWidget_2.setObjectName("listWidget_2")
        self.listWidget_4 = QtWidgets.QListWidget(self.groupBox_14)
        self.listWidget_4.setGeometry(QtCore.QRect(10, 235, 141, 121))
        self.listWidget_4.setObjectName("listWidget_4")
        self.label_43 = QtWidgets.QLabel(self.groupBox_14)
        self.label_43.setGeometry(QtCore.QRect(5, 220, 71, 16))
        self.label_43.setStyleSheet("font: 63 12pt \"FixedsysTTF\";")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.pushButton_66 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_66.setGeometry(QtCore.QRect(75, 360, 76, 26))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.pushButton_66.setFont(font)
        self.pushButton_66.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_66.setObjectName("pushButton_66")
        self.pushButton_67 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_67.setGeometry(QtCore.QRect(10, 360, 56, 26))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.pushButton_67.setFont(font)
        self.pushButton_67.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_67.setObjectName("pushButton_67")
        self.pushButton_68 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_68.setGeometry(QtCore.QRect(10, 180, 61, 26))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.pushButton_68.setFont(font)
        self.pushButton_68.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_68.setObjectName("pushButton_68")
        self.pushButton_69 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_69.setGeometry(QtCore.QRect(80, 180, 71, 26))
        font = QtGui.QFont()
        font.setFamily("FixedsysTTF")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(4)
        self.pushButton_69.setFont(font)
        self.pushButton_69.setStyleSheet("font: 32 11pt \"FixedsysTTF\";")
        self.pushButton_69.setObjectName("pushButton_69")

        self.retranslateUi()
        self.tabWidget_3.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_15.setTitle(_translate("Form", " EXCHANGES "))
        self.pushButton_6.setText(_translate("Form", "CONNECT"))
        self.pushButton_7.setText(_translate("Form", "X"))
        self.pushButton_8.setText(_translate("Form", "SAVE"))
        self.groupBox_22.setTitle(_translate("Form", " WALLET "))
        self.label_46.setText(_translate("Form", "EST. VALUE OF HOLDINGS"))
        self.label_47.setText(_translate("Form", "EUR"))
        self.label_48.setText(_translate("Form", "ETH"))
        self.groupBox_13.setTitle(_translate("Form", "TICKER:  "))
        self.pushButton_32.setText(_translate("Form", "BUY"))
        self.pushButton_33.setText(_translate("Form", "SELL"))
        self.label_39.setText(_translate("Form", "PRICE"))
        self.label_40.setText(_translate("Form", "AMOUNT"))
        self.label_41.setText(_translate("Form", "TOTAL"))
        self.groupBox_14.setTitle(_translate("Form", "ALGORITHMS "))
        self.label_43.setText(_translate("Form", "RUNNING"))
        self.pushButton_66.setText(_translate("Form", "STOP"))
        self.pushButton_67.setText(_translate("Form", "SHOW"))
        self.pushButton_68.setText(_translate("Form", "START"))
        self.pushButton_69.setText(_translate("Form", "DETAILS"))

