# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'explorer_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(967, 661)
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 961, 654))
        self.frame_4.setStyleSheet("font: 11pt \"Ubuntu\";")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.groupBox_11 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_11.setGeometry(QtCore.QRect(240, 5, 621, 151))
        self.groupBox_11.setStyleSheet("font: 11pt \"Ubuntu\";")
        self.groupBox_11.setObjectName("groupBox_11")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_11)
        self.textBrowser.setGeometry(QtCore.QRect(5, 25, 611, 121))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_12 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_12.setGeometry(QtCore.QRect(0, 5, 236, 646))
        self.groupBox_12.setStyleSheet("font: 11pt \"Ubuntu\";")
        self.groupBox_12.setObjectName("groupBox_12")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_12)
        self.comboBox_2.setGeometry(QtCore.QRect(115, 30, 116, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox.setGeometry(QtCore.QRect(10, 30, 81, 26))
        self.checkBox.setObjectName("checkBox")
        self.comboBox_11 = QtWidgets.QComboBox(self.groupBox_12)
        self.comboBox_11.setGeometry(QtCore.QRect(115, 65, 116, 26))
        self.comboBox_11.setObjectName("comboBox_11")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 65, 96, 26))
        self.checkBox_2.setObjectName("checkBox_2")
        self.listWidget_6 = QtWidgets.QListWidget(self.groupBox_12)
        self.listWidget_6.setGeometry(QtCore.QRect(5, 145, 226, 491))
        self.listWidget_6.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget_6.setObjectName("listWidget_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_2.setGeometry(QtCore.QRect(115, 115, 116, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.groupBox_21 = QtWidgets.QGroupBox(self.frame_4)
        self.groupBox_21.setGeometry(QtCore.QRect(240, 155, 716, 496))
        self.groupBox_21.setStyleSheet("font: 11pt \"Ubuntu\";")
        self.groupBox_21.setObjectName("groupBox_21")
        self.tableView_2 = QtWidgets.QTableView(self.groupBox_21)
        self.tableView_2.setGeometry(QtCore.QRect(5, 25, 706, 461))
        self.tableView_2.setObjectName("tableView_2")
        self.frame_20 = QtWidgets.QFrame(self.frame_4)
        self.frame_20.setGeometry(QtCore.QRect(865, 27, 91, 126))
        self.frame_20.setStyleSheet("font: 11pt \"Ubuntu\";")
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.pushButton_70 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_70.setGeometry(QtCore.QRect(5, 95, 81, 26))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_70.setFont(font)
        self.pushButton_70.setStyleSheet("font: 11pt \"Ubuntu\";")
        self.pushButton_70.setObjectName("pushButton_70")
        self.pushButton_72 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_72.setGeometry(QtCore.QRect(5, 65, 81, 26))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_72.setFont(font)
        self.pushButton_72.setStyleSheet("font: 11pt \"Ubuntu\";")
        self.pushButton_72.setObjectName("pushButton_72")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_11.setTitle(_translate("Form", " description"))
        self.groupBox_12.setTitle(_translate("Form", " search"))
        self.checkBox.setText(_translate("Form", "source"))
        self.checkBox_2.setText(_translate("Form", "category"))
        self.groupBox_21.setTitle(_translate("Form", " search results"))
        self.pushButton_70.setText(_translate("Form", "chart"))
        self.pushButton_72.setText(_translate("Form", "compare"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
