# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'news_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(966, 650)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 966, 646))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_38.setGeometry(QtCore.QRect(785, 5, 175, 26))
        self.lineEdit_38.setStyleSheet("")
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.tableView_8 = QtWidgets.QTableView(self.widget)
        self.tableView_8.setGeometry(QtCore.QRect(4, 38, 956, 601))
        self.tableView_8.setStyleSheet("")
        self.tableView_8.setObjectName("tableView_8")
        self.pushButton_45 = QtWidgets.QPushButton(self.widget)
        self.pushButton_45.setGeometry(QtCore.QRect(5, 5, 86, 26))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_45.setFont(font)
        self.pushButton_45.setStyleSheet("font: 11pt \"Ubuntu\";")
        self.pushButton_45.setObjectName("pushButton_45")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_45.setText(_translate("Form", "websites"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
